import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {createServer} from 'node:http';
import fs from 'node:fs/promises';
import express from 'express';
import {MongoClient} from 'mongodb';
import {MongoMemoryServer} from 'mongodb-memory-server';
import {createApp} from '../server/app.js';
import {MongoStore} from '../server/store.js';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE??'playwright');
let mongo,client,browser,server;
try {
  mongo=await MongoMemoryServer.create();client=new MongoClient(mongo.getUri());await client.connect();
  const store=new MongoStore(client.db('browser_test'));await store.initialize();
  server=createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const origin=`http://127.0.0.1:${server.address().port}`;
  const app=createApp({store,origin,staticDir:fileURLToPath(new URL('../dist/',import.meta.url))});
  app.use('/ui-lab',express.static(fileURLToPath(new URL('../../ui-lab/',import.meta.url))));
  app.use('/handbook',express.static(fileURLToPath(new URL('../../../../interview-handbook/',import.meta.url))));
  server.on('request',app);
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
  const page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(origin);await page.getByRole('button',{name:'Create an account',exact:true}).click();
  await page.getByLabel('Email',{exact:true}).fill('browser@example.test');
  await page.getByLabel('Password',{exact:true}).fill('correct horse battery');await page.getByRole('button',{name:'Register',exact:true}).click();
  await page.getByRole('heading',{name:'Task board',exact:true}).waitFor();
  await page.getByLabel('Title',{exact:true}).fill('Browser task');await page.getByRole('button',{name:'Add task',exact:true}).click();
  await page.getByRole('heading',{name:'Browser task',exact:true}).waitFor();
  await page.getByLabel('Status for Browser task',{exact:true}).selectOption('done');
  await page.getByText('Status: done · Version 1',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Reading list',exact:true}).click();
  await page.getByLabel('Title',{exact:true}).fill('React reference');await page.getByLabel('URL',{exact:true}).fill('https://react.dev/learn');
  await page.getByRole('button',{name:'Add bookmark',exact:true}).click();await page.getByRole('link',{name:'Open reference'}).waitFor();
  await page.getByRole('button',{name:'Expense tracker',exact:true}).click();
  await page.getByLabel('Title',{exact:true}).fill('Browser book');await page.getByLabel('Amount in INR').fill('12.34');await page.getByLabel('Date',{exact:true}).fill('2026-10-08');
  await page.getByRole('button',{name:'Add expense',exact:true}).click();await page.getByRole('heading',{name:'Browser book'}).waitFor();
  await page.getByText(/All-time total:.*12.34/).waitFor();
  await page.setViewportSize({width:375,height:812});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'MERN mobile overflow');
  const out=fileURLToPath(new URL('../../../../tmp/browser/',import.meta.url));await fs.mkdir(out,{recursive:true});await page.screenshot({path:`${out}/workspace-mobile.png`,fullPage:true});
  await page.reload();await page.getByRole('heading',{name:'Task board',exact:true}).waitFor();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('heading',{name:'Sign in',exact:true}).waitFor();
  await page.goto(`${origin}/ui-lab/`);
  const accordion=page.getByRole('button',{name:'What is a closure?'});await accordion.focus();await page.keyboard.press('Enter');
  assert.equal(await accordion.getAttribute('aria-expanded'),'true');
  const trigger=page.getByRole('button',{name:'Open study reminder'});await trigger.click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');
  assert.ok(await trigger.evaluate(element=>element===document.activeElement),'Dialog focus return');
  await page.getByLabel('Task title').fill('Undo task');await page.getByRole('button',{name:'Add task',exact:true}).click();
  await page.getByRole('button',{name:'Delete Undo task'}).click();await page.getByRole('button',{name:'Undo last deletion'}).click();
  await page.getByText('Undo task',{exact:true}).waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'UI lab mobile overflow');
  await page.screenshot({path:`${out}/ui-lab-mobile.png`,fullPage:true});
  await page.goto(`${origin}/handbook/study.html`);await page.getByText('100 questions',{exact:true}).waitFor();
  await page.getByLabel('Search questions').fill('closure');
  assert.ok(await page.locator('article').count()>0,'Question filtering');
  await page.locator('article select').first().selectOption('2');await page.reload();
  assert.ok(await page.locator('article select').evaluateAll(elements=>elements.some(el=>el.value==='2')),'Progress survives reload');
  assert.deepEqual(errors,[]);console.log('PASS: real-browser registration, task version, bookmarks, exact expenses, reload, logout, accordion keyboard, dialog focus, undo, mobile widths, study filtering and progress.');
} finally {
  if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));if(client)await client.close();if(mongo)await mongo.stop();
}
