"""Format ten original failure cases; broken examples are educational fixtures."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
CASES=[
('javascript','Shallow copy mutates the original','javascript',"const a={tags:['mern']}; const b={...a}; b.tags.push('node'); console.log(a.tags.length);",'Original list stays at length 1.','Length becomes 2.','Which references are copied? Inspect a.tags === b.tags.',"const a={tags:['mern']}; const b={...a,tags:[...a.tags,'node']}; console.log(a.tags.length);",'The outer object is copied while tags is still shared. Clone or replace the nested value at the domain boundary.','Define mutation ownership and test nested values, not just outer identity.'),
('react','An effect stores a derived total','jsx',"const [total,setTotal]=useState(0);\nuseEffect(()=>setTotal(items.reduce((s,x)=>s+x.cents,0)),[items,total]);",'Total corresponds to the current items without redundant transitions.','The component performs redundant renders and can create feedback when derivation changes.','Is total an independent fact? Does an external system need synchronization?',"const total=items.reduce((sum,item)=>sum+item.cents,0);",'A derived value was modeled as separate state and synchronized through an effect. Calculate it from current inputs.','Store independent facts and reserve effects for external synchronization.'),
('nodejs','Async code blocks all requests','javascript',"app.get('/report',async(req,res)=>{\n  const result=expensiveSynchronousComputation();\n  res.json(result);\n});",'Other requests remain responsive during a report.','Unrelated request latency rises while JavaScript computes.','Profile CPU and event-loop delay. What does async actually change?',"// Architecture fix: submit bounded work to a worker/job executor.\nconst job=await jobs.submit(validatedReportInput);\nres.status(202).json({jobId:job.id});",'async changes return/await behavior; it does not move synchronous computation off the executing thread.','Bound work and profile the actual bottleneck. This solution is pseudocode requiring a job system.'),
('express','API routes return HTML','javascript',"app.use(express.static('dist'));\napp.get('/{*splat}',(req,res)=>res.sendFile(appShell));\napp.get('/api/tasks',listTasks);",'API paths return JSON or a safe API error.','GET /api/tasks receives the app shell.','Which matching handler responds first?',"app.get('/api/tasks',listTasks);\napp.use('/api',(req,res)=>res.status(404).json({error:{code:'NOT_FOUND'}}));\napp.use(express.static('dist'));\napp.get('/{*splat}',(req,res)=>res.sendFile(appShell));",'The catch-all handler terminated the request before the API route. Express 5 route syntax is shown.','Keep the API boundary before the SPA fallback and test an unknown API path.'),
('mongodb','Duplicate creation passes a precheck','javascript',"if (!await users.findOne({email})) await users.insertOne({email});",'At most one stored record per canonical email.','Two concurrent requests both pass the read and insert.','Can another request act between the read and insert?',"await users.createIndex({email:1},{unique:true});\n// Insert and translate a real duplicate-key error into a safe conflict.\nawait users.insertOne({email});",'A read-before-write observation is not a uniqueness invariant. The database index establishes it.','Normalize the value consistently, verify the actual index, and test real competing inserts.'),
('mongoose','Unique is treated as field validation','javascript',"const schema=new Schema({email:{type:String,unique:true}});\nawait new User({email}).validate(); // assumed to prove uniqueness",'Concurrent duplicates are rejected by the real store.','Document validation alone does not prove uniqueness.','Is unique a validator, and does the index exist?',"await User.init(); // wait for configured indexes in a controlled test\n// In deployment, use an explicit index migration and handle duplicate-key errors.", 'unique describes an index requirement, not an ordinary Mongoose validator. Production index deployment needs intentional management.','Separate field validation from persisted uniqueness and inspect index creation failures.'),
('api','Another user can read a guessed id','javascript',"const item=await items.findOne({_id:validatedId});\nres.json(item);",'A caller can read only permitted items.','A valid id exposes another owner\'s record.','Where did the trusted caller identity enter the query?',"const item=await items.findOne({_id:validatedId,owner:req.user.id});\nif(!item) return res.status(404).json({error:{code:'NOT_FOUND'}});\nres.json(toPublicItem(item));",'Resource lookup omitted permission scope. An opaque id is not authorization.','Include ownership or membership on every operation and test reads as well as writes.'),
('git','A reviewed change omitted an unstaged file','bash',"git add server/app.js\ngit commit -m 'Add validation'\n# validation.js was modified but never staged",'The commit includes the coherent behavior and required file.','The new commit imports a function whose implementation is absent.','Compare working, staged, and committed states.',"git status --short\ngit diff\ngit diff --cached\n# Stage intended missing files, review, and commit a correction.", 'A commit records the index, not every working-tree change.','Inspect the staged diff and run checks on a clean checkout or CI.'),
('docker','Container connects to its own loopback','text',"MONGO_URI=mongodb://127.0.0.1:27017/app\n# app and mongo run in separate Compose containers",'The application reaches the database service.','Connection is refused inside the app container.','Which network namespace owns 127.0.0.1?',"MONGO_URI=mongodb://mongo:27017/app\n# Use the actual Compose service name on its shared private network.",'Loopback inside the app container refers to that container, not the separate database.','Document network topology, readiness, credentials, and private service names.'),
('deployment','Development proxy hides a missing production route','text',"Development: /api/tasks -> Vite proxy -> backend\nProduction: static host serves only dist/",'Production requests reach an authenticated API contract.','The deployed page loads but /api/tasks fails or returns HTML.','Does the deployed environment have the proxy and server runtime?',"Deploy the backend and configure same-origin API routing, or configure a deliberate separate origin with its security policy.\nVerify /api/tasks status/content type and an authorized write in the deployed topology.",'The development proxy was mistaken for deployed infrastructure.','Document runtime and routing requirements and smoke-test the actual deployment.'),
]
index='# Debugging library\n\nPredict the broken result before revealing a solution. Some fragments assume a surrounding application and some fixes describe an architecture rather than pretending to be complete code. Never run destructive or security-weakening commands to satisfy a reproduction.\n\n'
out=ROOT/'knowledge-base/debugging';out.mkdir(parents=True,exist_ok=True)
for id,title,language,broken,expected,actual,hint,solution,root,prevent in CASES:
    index+=f'- [{title}]({id}.md) — {id}\n'
    text=f'# {title}\n\nPriority: P0 for failure reasoning; technology prerequisites follow the [topic guide](../topics/{id if id not in ["docker","deployment"] else "devops"}.md).\n\n## Broken code\n\n```{language}\n{broken}\n```\n\n## Expected behavior\n\n{expected}\n\n## Actual behavior\n\n{actual}\n\n## Hints\n\n{hint}\n\n## Solution\n\n<details>\n<summary>Reveal the correction</summary>\n\n```{language}\n{solution}\n```\n\n</details>\n\n## Explanation and root cause\n\n{root}\n\n## How to prevent it\n\n{prevent}\n\n## Verification\n\nReproduce the actual behavior, apply the fix in the stated runtime, and assert the expected behavior with the relevant boundary: pure output, real database, browser, Git snapshot, or deployment topology. [Existing scenario bank](../../interview-handbook/scenarios/README.md) provides additional cases.\n\n[All challenges](README.md)\n'
    (out/f'{id}.md').write_text(text,encoding='utf-8')
(out/'README.md').write_text(index,encoding='utf-8')
print('Built 10 original debugging cases.')
