"""Generate the original interview handbook from reviewable structured source.

Run with Python 3.11+. This script does not scrape or copy external courses.
"""
from pathlib import Path
import json, csv, html

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / 'interview-handbook'

def write(path, text):
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text.strip() + '\n', encoding='utf-8')

# Each answer is original preparation guidance, not a claimed company question.
QUESTIONS = {
'html-css': [
('Easy','Why use a button instead of a clickable div?','A button has keyboard activation, focus behavior, a role, and a disabled state built in. A div needs those behaviors implemented separately. Use type="button" inside a form when the action should not submit. Test with Tab, Enter, and Space.','How would you make a toggle announce its state?'),
('Easy','What is the difference between an id and a class?','An id identifies one element in a document and can connect a label to a form control or a fragment link to a section. Classes group elements for styling and scripting. Duplicate ids make these relationships ambiguous. Prefer classes for reusable styles.','How does specificity differ?'),
('Easy','Explain the CSS box model.','An element has content, padding, border, and margin. With content-box, the declared width covers content; padding and borders add to the rendered width. With border-box they are included. Margins remain outside in either case.','Why can two vertical margins collapse?'),
('Medium','When would you choose Grid over Flexbox?','Grid manages tracks in two dimensions and is useful for page layouts or aligned card rows and columns. Flexbox distributes items along one main axis and works well for toolbars. A grid item can itself be a flex container; choose based on the alignment constraint.','How does minmax(0,1fr) prevent overflow?'),
('Medium','Why is z-index 999999 still behind a modal?','z-index compares elements inside their stacking context. A descendant cannot escape an ancestor context merely by increasing its own value. Inspect positioned ancestors, transforms, opacity, and isolation. Native dialog top-layer behavior is a separate mechanism.','Which properties create a stacking context?'),
('Medium','How do you build an accessible form?','Associate visible labels with controls, choose input types and autocomplete values, group related controls with fieldset and legend, and connect error text with aria-describedby. Preserve entered values after failure. Client validation improves feedback; the server validates independently.','Where should focus move after a failed submission?'),
('Medium','What does the cascade actually decide?','For declarations that apply to an element, the cascade considers origin and importance, cascade layers, specificity, and ordering, with additional rules for scoped styles. Specificity alone cannot explain every result. Inspect computed styles before adding !important.','What changes for important declarations in layers?'),
('Hard','How do you debug layout shift?','Record a browser performance trace and inspect layout-shift entries. Reserve space for media, avoid inserting late content above what users are reading, and review font loading. A shift caused by recent user interaction may be treated differently in the metric; measure the actual experience.','How do you reserve image space responsively?'),
('Hard','How should a modal manage focus?','On opening, move focus into the dialog to a useful target; keep keyboard navigation within the active modal and provide an accessible name. On close, return focus to the trigger if it remains usable. Prefer the native dialog API and test Escape and background interaction.','What happens if the trigger is removed?'),
('Hard','How do you make a table usable on a phone?','Keep header relationships and readable text. A horizontal scroll container can preserve a true data table; give users a clear scroll affordance. For a card view, repeat the labels and preserve reading order. Choose based on whether cross-row comparison is essential.','How would you test at 200 percent zoom?')],
'javascript': [
('Easy','What does const guarantee?','const prevents reassignment of the binding. It does not freeze the object it references. const user = {name:"A"}; user.name = "B" is valid. Object.freeze is shallow, so nested objects still need an explicit immutability strategy.','What is the temporal dead zone?'),
('Easy','Compare strict equality and Object.is.','Strict equality avoids type coercion, considers +0 and -0 equal, and considers NaN unequal to itself. Object.is considers NaN equal to itself and distinguishes signed zeros. Choose a comparison that matches the domain rather than assuming one is universally better.','What does a Set do with NaN?'),
('Easy','Explain a closure with a useful example.','A function retains access to the lexical environment where it was created. A counter factory can keep a private count and return an increment function. Two factory calls create separate environments. Closures are also why an old callback may see an earlier render value.','Can a closure retain a large object?'),
('Medium','Predict synchronous logs, a promise, and a timer.','In a normal browser script, synchronous code finishes first. Promise reaction jobs run at the microtask checkpoint before the next timer task. setTimeout(fn,0) makes a callback eligible later; it does not interrupt the current stack. Do not generalize this ordering to every Node phase.','Can recursive microtasks starve rendering?'),
('Medium','Why does spreading an object not deep clone it?','Object spread copies own enumerable properties into a new object. Nested object references still point to the same objects. structuredClone supports many structured values but cannot clone functions. For React state, copy only the path being changed or use an appropriate immutable update tool.','What happens to a Date in JSON serialization?'),
('Medium','Compare debounce and throttle.','Debounce waits for a quiet period and is useful for search inputs. Throttle limits execution frequency and is useful for continuous scroll work. Specify leading and trailing behavior, cancellation, and what happens to this and arguments; those are part of the function contract.','How would you flush the pending call?'),
('Medium','Compare Promise.all and Promise.allSettled.','Promise.all resolves with ordered results only when every input fulfills and rejects when an input rejects. It does not cancel other operations. allSettled waits for all inputs and reports each outcome. Bound concurrency for large input lists instead of starting thousands at once.','How can AbortController help cancellation?'),
('Hard','How does this behave in arrow functions?','An arrow function captures this lexically. A normal function gets this from the invocation form, such as obj.method(), and a detached method loses that receiver. bind creates a function with a fixed receiver. Arrow functions cannot be constructors.','Why can an arrow method be wrong on a prototype?'),
('Hard','How would you implement an LRU cache?','Use a Map for insertion order. On get, remove and reinsert the entry to mark it recent. On set, replace any existing entry and evict the first key when over capacity. Average operations are constant time under the usual hash-map model. Validate capacity and distinguish missing keys from stored undefined.','How would you add TTL without unbounded timers?'),
('Hard','What causes memory leaks in browser code?','A leak is memory retained longer than needed: global caches with no eviction, listeners on long-lived objects, timers holding closures, or subscriptions not removed. Compare heap snapshots after repeating a flow. Removing a DOM node alone does not release references held elsewhere.','How would you prove that a fix works?')],
'react': [
('Easy','What is the difference between props and state?','Props are inputs supplied by a parent. State is component-owned memory that participates in rendering. Treat both as immutable snapshots. Derive values from existing inputs during render when possible instead of keeping duplicate state that can drift.','When should state be lifted?'),
('Easy','Why do list items need stable keys?','Keys tell React which sibling identity persists across renders. A stable domain id preserves the correct item state when ordering changes. Array indexes can assign state to the wrong row after insertion or sorting. Keys only need to be unique among siblings.','Can changing a key reset a form?'),
('Easy','Why does setCount(count + 1) twice often add only one?','Both calls can read the same state snapshot in the event handler. Functional updates setCount(c => c + 1) describe transitions and can be applied in sequence. The state variable in the current handler does not mutate immediately after a setter.','What does batching change?'),
('Medium','What belongs in useEffect?','Use an effect to synchronize with an external system such as a subscription, network request, or browser API. User actions usually belong in event handlers. Filtering an existing array can happen during render. Return cleanup for resources acquired by the effect.','Why might development run setup and cleanup again?'),
('Medium','How do you avoid stale search responses?','Associate the request with the current query, abort obsolete fetches during cleanup, and ignore responses from older requests. Cancellation can reduce work; an identity or generation check protects correctness even if an operation cannot be canceled. Keep loading and error state tied to the same request.','What happens when the user clears the query?'),
('Medium','When would you use a reducer?','A reducer makes related state transitions explicit, especially when several fields change together. Keep the reducer pure and represent actions using domain intent. It can make undo or optimistic transitions easier to inspect. A single simple boolean does not need a reducer.','Where do asynchronous operations belong?'),
('Medium','Does context prevent renders?','Context distributes a value. Consumers can render when the provided value changes, and normal parent rendering also matters. Split unrelated contexts and keep provider values stable where useful. Measure before adding memoization; context is not a complete server-data cache.','When would an external store help?'),
('Hard','How do you handle optimistic updates safely?','Apply a temporary local result while a request is pending. Use a mutation id or version so an earlier response cannot overwrite a later edit. On failure, restore the affected item or refetch authoritative state and show a retry path. Disabling duplicate submission simplifies some flows.','How do you handle a 409 version conflict?'),
('Hard','How do you improve a slow React list?','Measure whether the cost is fetching, rendering, layout, or large data processing. Use server pagination or windowing for large collections, stable keys, and appropriate state placement. Memoization helps only when avoided work exceeds comparison cost and props remain suitably stable.','How do you preserve accessibility in virtualization?'),
('Hard','Compare client components and server components.','Client components support state and browser interactions. Server components execute in a compatible server-rendering framework and can access server resources without shipping that implementation to the browser. A Vite client SPA does not gain server components by installing React.','How do you keep secrets out of client bundles?')],
'node-express': [
('Easy','What does Node add to JavaScript?','Node is a runtime with APIs for processes, files, networking, and other server tasks. Browser DOM APIs are not generally available. Nonblocking I/O lets a process handle many waiting operations, but synchronous JavaScript work still occupies the main execution thread.','Which APIs use the worker pool?'),
('Easy','What is Express middleware?','Middleware receives the request, response, and next function. It may finish the response or pass control onward. Ordering matters: JSON parsing before routes, authentication before protected handlers, and error handlers after routes. Calling next after sending a response can create double-response bugs.','How is error middleware identified?'),
('Easy','Why must input validation run on the server?','Clients can be modified or bypassed. Validate types, lengths, allowed values, and relationships at the API boundary. Use an allowlist when constructing database writes and return an actionable validation error. Database constraints remain necessary for races and persistent invariants.','Should you pass req.body directly into an update?'),
('Medium','How do Express 4 and Express 5 differ for async errors?','Express 5 forwards rejected promises returned from route handlers to error middleware. Express 4 handlers usually need an explicit wrapper or try/catch with next(error). Use the behavior of the installed major version and test a thrown asynchronous error.','Why should unexpected errors not expose stacks?'),
('Medium','When should you use a stream?','Streams process a sequence without loading the complete payload into memory. Respect backpressure when the receiver cannot keep up. pipeline coordinates completion and error handling. A stream helps large files; it does not make CPU-heavy parsing automatically inexpensive.','How does a client disconnect affect a response stream?'),
('Medium','How do you shut down an API gracefully?','Stop accepting new requests, let in-flight work finish within a deadline, close database and queue connections, and exit. Handle termination signals and readiness separately from liveness. Long-lived sockets require an explicit policy so shutdown cannot hang forever.','What happens during a rolling deployment?'),
('Medium','How do you diagnose a blocked event loop?','Correlate latency spikes with CPU profiles and event-loop delay metrics. Look for synchronous filesystem calls, large JSON work, catastrophic regexes, or expensive computations. Split or offload CPU work to worker threads and set payload limits. More async keywords cannot fix synchronous CPU work.','How would you benchmark a proposed fix?'),
('Hard','How should rate limits work across multiple instances?','Per-process limits are useful locally but do not give one consistent global budget. Use a shared store or gateway and choose a key, window algorithm, and outage policy. Be careful with forwarded IP headers: trust only known proxy configuration.','How would you limit by both account and IP?'),
('Hard','How do you safely retry an API request?','Retry transient failures with a bounded attempt count, timeout, exponential backoff, and jitter. Retrying a write can duplicate side effects, so use idempotency keys or a domain uniqueness constraint. A validation failure should not be retried automatically.','How do you distinguish timeout from definitive failure?'),
('Hard','What should structured API logs contain?','Include a request or trace id, route template, status, duration, and a safe error category. Redact passwords, authorization headers, session tokens, and sensitive personal data. Structured fields enable aggregation; logging every request body risks exposing data and increases cost.','How do you correlate logs across services?')],
'mongodb': [
('Easy','When should you embed rather than reference?','Embed bounded data that is read and updated with its parent. Reference independently owned entities or collections that grow without a useful bound. Model around access patterns and update invariants. MongoDB is flexible, but an application still needs schema and migration discipline.','How would you model comments on a popular post?'),
('Easy','What does an index do?','An index maintains an ordered access structure so queries can locate matches without scanning every document. It consumes storage and adds write work. Inspect explain output on realistic data to see whether the index supports the actual filter and sort.','Why does indexing every field hurt?'),
('Easy','Is Mongoose unique a validator?','unique declares an index intention. The database unique index enforces uniqueness and concurrent duplicate writes may produce E11000. Ensure the index exists and translate the conflict into an appropriate API response. An earlier findOne check alone is race-prone.','What about existing duplicates before adding the index?'),
('Medium','Explain a compound index.','A compound index orders multiple fields. Its prefixes and key order affect which queries can use it efficiently. For a user-owned feed, {owner:1, createdAt:-1, _id:-1} can support a constrained ordered listing. Check filters, sort, and scanned keys rather than choosing an index from intuition alone.','How does a range predicate change your index choice?'),
('Medium','Compare offset and cursor pagination.','Offset pagination is simple and allows page numbers, but large offsets do extra work and concurrent inserts can shift boundaries. Cursor pagination seeks after a stable sort tuple and is useful for feeds. Include a tie-breaker such as id and validate cursor format and scope.','Can users jump to page 50 with a cursor?'),
('Medium','When do you need a transaction?','Single-document writes are atomic. A transaction is useful when a business invariant spans multiple documents and all changes must commit together. Transactions require a supported deployment, typically a replica set or sharded cluster. They add coordination cost and still need appropriate retry handling.','Can embedding remove the transaction requirement?'),
('Medium','What does lean do in Mongoose?','lean returns plain objects instead of hydrated documents for a query. This can reduce memory and processing for read-only paths. Document methods and standard hydration behavior are absent, so check getters, virtuals, and serialization expectations before enabling it.','Would you use lean for a document you intend to save?'),
('Hard','How do you prevent selling the same last item twice?','Use an atomic conditional update whose filter includes available stock, with an increment or decrement in the same operation. A read-then-write sequence races. If payment and reservation span services, design expiration, idempotency, and compensation rather than assuming one database transaction covers them.','How would you release an expired reservation?'),
('Hard','How do you detect and prevent lost updates?','Include an expected version in the update predicate and increment it atomically. If no document matches, distinguish missing or unauthorized data from an owned version conflict without revealing another user\'s data. Tell the client to reload or resolve the conflict.','Can a timestamp be a reliable version token?'),
('Hard','What can make an aggregation slow?','Large input cardinality, early fan-out, expensive sorts, broad lookups, and insufficiently selective predicates can cause work and memory pressure. Use explain, realistic sample data, suitable indexes, and early filters where semantically valid. Avoid returning unbounded results to the client.','When would you precompute a summary?')],
'security-api': [
('Easy','Compare authentication and authorization.','Authentication establishes who the caller is. Authorization decides whether that caller may perform an action on a resource. Every protected database operation should enforce ownership or role scope. A hidden UI button is not an authorization check.','Why is checking only the route id insufficient?'),
('Easy','Why hash passwords rather than encrypt them?','A password verifier should not require recovering the original password. Use a password hashing function with a unique salt and appropriate work parameters. Store the encoded parameters for upgrades. Never use a plain fast digest alone or log the password during debugging.','How do you migrate work factors?'),
('Easy','What does CORS protect?','CORS controls browser access to cross-origin responses. It is not API authentication and does not stop server clients from making requests. Some cross-origin requests can still be sent even when reading the response is blocked. Cookie-based writes need a deliberate CSRF strategy.','Why can CORS alone fail to prevent CSRF?'),
('Medium','Where should a browser session token live?','An HttpOnly cookie prevents JavaScript from reading the token and can reduce token theft through XSS. Use Secure over HTTPS and an appropriate SameSite setting. Cookie authentication also needs CSRF defenses and revocation. Browser storage tradeoffs should be discussed with the threat model.','Does HttpOnly stop malicious scripts making requests?'),
('Medium','Why are JWTs not encrypted by default?','A usual signed JWT protects integrity, not confidentiality. Its payload is encoded and readable. Verify signature, allowed algorithms, expiration, issuer, and audience as appropriate. Revocation and rotation require a design; long-lived bearer tokens increase exposure.','How would you revoke one compromised session?'),
('Medium','How do you prevent NoSQL injection?','Construct filters from validated scalar fields rather than accepting arbitrary objects from the client. Reject unexpected operators and properties, limit lengths, and use explicit update fields. A schema library helps at the boundary but cannot repair a deliberately unsafe filter construction.','What is mass assignment?'),
('Medium','What makes a REST error useful?','Use a consistent status and a machine-readable error code with a safe human message. Include a correlation id for unexpected errors and field-level detail for validation failures. Avoid leaking stack traces, password hashes, or resource existence across authorization boundaries.','When would you return 409 rather than 400?'),
('Hard','How do you stop an SSRF attack?','Treat server-side fetching of user URLs as a privileged operation. Restrict destinations, schemes, redirects, and resolved IPs, block internal networks, and use egress controls and timeouts. Validation before a redirect or DNS change is not enough. A bookmark app can simply store URLs without fetching them.','How would you handle DNS rebinding?'),
('Hard','How do you make a payment webhook idempotent?','Verify the provider signature against the expected raw body, persist a unique event or operation id, and apply state changes atomically with that record. Handle out-of-order events and delayed retries. Return success only under a defined durable handling contract.','Why is an in-memory Set insufficient?'),
('Hard','How do you make file uploads safer?','Limit size and count, validate expected types using content as well as names, generate server filenames, store outside executable paths, and isolate processing. Apply malware scanning where relevant and authorize access to private files. Streaming and timeouts protect resources.','Can MIME type from the client be trusted?')],
'testing-tooling': [
('Easy','What should a unit test verify?','A unit test checks an observable behavior of a small unit with controlled inputs. Cover boundaries and errors, not just the happy path. Tests that repeat the implementation algorithm can pass despite the same bug. Use explicit expected outcomes or an independent model.','What makes a test brittle?'),
('Easy','What belongs in an integration test?','Check the contract between real cooperating pieces, such as HTTP parsing, authorization, service logic, and persistence. An in-memory repository is useful for route behavior but cannot establish MongoDB index or atomicity behavior. Label that distinction in the test report.','Which dependencies should remain real?'),
('Easy','Why commit package-lock.json?','The lockfile records the resolved dependency graph and integrity information. npm ci installs from it without rewriting resolutions and fails if the manifest disagrees. A lockfile improves reproducibility but does not eliminate vulnerabilities or runtime incompatibility.','How do you update dependencies deliberately?'),
('Medium','How should React tests select elements?','Prefer accessible roles and names because they reflect how users interact. Test an action and its visible result. Avoid selectors coupled to internal component structure unless necessary. Add browser tests for focus, layout, navigation, and behaviors that a simulated DOM does not model well.','When is a test id justified?'),
('Medium','How do fake timers help debounce tests?','Advance a controlled clock to assert no call before the quiet period, a call after it, and cancellation behavior. Verify arguments and this preservation. Avoid arbitrary real sleeps that make the suite slow and flaky. Restore the clock after the test.','How do microtasks interact with your test clock?'),
('Medium','How do you test authorization?','Create two users and resources for each. Attempt every read, update, and delete as the other user and as an unauthenticated caller. Verify both status codes and unchanged data. Include list endpoints because they can leak records even if item routes are protected.','How do you test role escalation?'),
('Medium','What makes a useful CI pipeline?','Run deterministic checks for documentation, unit and API tests, and production builds. Add database integration tests when persistence invariants matter. Keep installation reproducible with lockfiles and grant minimal permissions. A green build only proves the checks that actually ran.','Which checks need secrets?'),
('Hard','How do you test concurrency bugs?','Run competing operations against the actual persistence layer, start them together, and assert the invariant after both complete. For stock, total successful reservations must not exceed initial quantity. For version edits, only one write at the same expected version should succeed.','Why may a fake repository hide the race?'),
('Hard','What does test coverage not tell you?','Coverage reports which code was executed, not whether assertions establish correctness. A high percentage can coexist with missing authorization or boundary tests. Review risk-based cases, mutation behavior, and failures before using coverage as a quality proxy.','How can mutation testing expose weak assertions?'),
('Hard','How do you test a production build?','Build with the actual toolchain, serve the generated assets, and exercise critical flows against the intended API mode. Check base paths, missing assets, client routing fallback, and environment variables. Development success does not prove deploy-time settings work.','Which variables become public in a client bundle?')],
'system-design': [
('Easy','How should a design interview start?','Clarify users, core operations, scale assumptions, correctness needs, and constraints. State which numbers are hypothetical. Sketch the simplest design that meets those requirements, then discuss where it fails. Listing technologies before the problem is clear makes tradeoffs difficult to defend.','Which requirement would change your design most?'),
('Easy','Compare latency and throughput.','Latency is time per operation; throughput is operations completed per unit time. Increasing concurrency can improve throughput until a bottleneck is saturated, while making latency worse. Report distributions such as p95 and p99, not just averages, and include failures.','What does queueing do near saturation?'),
('Easy','What can a cache get wrong?','A cache can serve stale data, expose data across users if keyed incorrectly, or overload the origin when many entries expire. Define freshness, key scope, capacity, and invalidation. For private responses, authorization and tenant identity remain part of the contract.','What is a cache stampede?'),
('Medium','How would you design notifications?','Persist notification intent or use an outbox with the business write, then let workers deliver asynchronously. Track attempts and unique operation ids, use bounded retries, and separate delivery from user read status. At-least-once delivery requires idempotent consumers.','How do you prevent duplicate emails?'),
('Medium','When would you use a queue?','Use a queue for work that can happen after the request, such as report generation. Define acknowledgment, retry, ordering, capacity, and dead-letter handling. A queue moves and buffers work; it does not remove the need to handle overload or failures.','How would the user see job progress?'),
('Medium','How do you scope a multitenant API?','Establish the tenant from trusted authentication or verified membership. Include tenant scope in every relevant query, index, cache key, and background job. Reject client attempts to assign ownership. Test with multiple tenants and cover administrative paths.','How would you model shared resources?'),
('Medium','How do you design a search endpoint?','Start with exact requirements: prefix, substring, ranking, and dataset size. Bound query length and result count, choose an index-supported strategy, and measure. Escaped regex may protect correctness but still scan many records. A dedicated search engine adds operations and consistency tradeoffs.','When is a Mongo text index enough?'),
('Hard','Explain an outbox pattern.','In one database transaction, persist both the business change and an event record. A publisher delivers unpublished records and marks progress. Delivery can repeat if a crash occurs between publishing and marking, so downstream consumers still deduplicate. Monitor backlog and failed records.','How do you preserve per-entity ordering?'),
('Hard','How do you design a rate limiter?','Choose a policy such as token bucket based on burst and sustained-rate requirements. Update shared state atomically, define keys and quotas, and make an explicit store-outage policy. Measure fairness and provide retry guidance. A fixed window can permit bursts around its boundary.','How would you support per-plan limits?'),
('Hard','How do you approach a region outage?','Clarify recovery time and acceptable data loss. Discuss replication lag, routing, backups, failover authority, and writes during partition. Exercise recovery procedures rather than assuming backups are restorable. Consistency and availability choices depend on the operation and business invariant.','How would you avoid two active writers?')],
'dsa-machine-coding': [
('Easy','How do you solve Two Sum in JavaScript?','Scan once with a Map from value to earlier index. For each value, check whether its complement is already present before inserting it. This avoids using one item twice. Expected time is O(n), space O(n). Test duplicate values and no-solution behavior.','What if the input is sorted?'),
('Easy','When is a sliding window appropriate?','A window works when adjacent ranges can be updated incrementally and a valid shrinking or expansion rule exists. For longest substring without repetition, track counts or latest indexes. For arbitrary sums with negative values, a simple increasing-sum window may be invalid.','Why do negative numbers break some window rules?'),
('Easy','How do you begin a machine coding round?','Clarify the required behavior and data contract, write a short acceptance checklist, and deliver one complete interaction early. Use semantic controls and separate core state logic from rendering. Reserve time for failure states and a demo instead of polishing before the main flow works.','What would you cut with ten minutes left?'),
('Medium','How do you implement a keyboard autocomplete?','Track query, matching results, active option, and expanded state. Support arrows, Enter, Escape, and appropriate combobox relationships. Avoid stale async responses and preserve focus on the input. Test an empty list and selection after the list changes.','How do you announce the result count?'),
('Medium','How do you flatten a nested tree?','Traverse recursively or with an explicit stack and carry the parent path or depth. State whether input order must be preserved and whether cycles are possible. Recursion uses stack space proportional to depth; an explicit stack avoids call-stack overflow for deeply nested inputs.','How do you handle duplicate ids?'),
('Medium','How do you implement undo in a task list?','Represent edits as commands or retain bounded prior states. Decide whether undo applies to local unsaved changes or to server-persisted operations. Give deleted items a stable id and protect against later conflicting changes. Announce the undo action and expiration clearly.','What happens after a page reload?'),
('Medium','How would you test a sortable data table?','Test text, numeric, and date comparisons, ties, direction changes, and mutation safety. Use a stable tie-breaker where order matters. Keep sort state explicit and announce the active sort with aria-sort. Test pagination interactions because sorting only the visible page can mislead users.','What is the locale policy?'),
('Hard','How do you build a concurrency-limited promise pool?','Keep at most k workers. Each worker claims a next index and awaits one task before claiming another. Store results at the original index and define error behavior. A fail-fast pool must still account for already-running tasks; a limit is not automatic cancellation.','What if one task never resolves?'),
('Hard','How do you implement an event emitter?','Map each event name to listeners, return an unsubscribe function, and decide how duplicate listeners behave. Iterate a snapshot so a listener removing another does not unexpectedly alter the current dispatch. Define exception and once semantics explicitly.','Should newly added listeners fire during current emission?'),
('Hard','How do you defend your coding solution?','Explain the state model, a core invariant, the expected complexity, and one rejected alternative. Demonstrate a boundary input and failure recovery. Identify what remains incomplete and how you would test it. Unsupported claims of production readiness weaken an otherwise good implementation.','What did you intentionally omit?')],
'typescript-career': [
('Easy','What does TypeScript guarantee at runtime?','Type annotations are erased and do not validate network responses at runtime. TypeScript catches many static mistakes when types are accurate. Parse unknown external values with runtime checks before trusting them. Avoid asserting a type merely to silence a compiler error.','Why is unknown safer than any?'),
('Easy','Compare an interface and a type alias.','Both can describe object shapes. Interfaces support declaration merging and extension; aliases also represent unions, primitives, and other type expressions. Use a consistent convention and choose the feature required by the design. Neither creates runtime data or validation.','How would you represent loading, success, and error?'),
('Easy','How should you explain a portfolio project?','State the user problem, your contribution, the key design choice, and a demonstrable result. Distinguish measurements from assumptions. Point to working source, tests, and setup instructions. Do not claim users, revenue, or latency numbers that you did not measure.','Which part would you redesign?'),
('Medium','What is a discriminated union useful for?','A shared literal field lets the compiler narrow a value to a particular variant. A request state can have idle, loading, success with data, or error with a message. This prevents combinations such as success without data that arise from independent booleans.','How do you check exhaustiveness with never?'),
('Medium','How do generics improve reusable functions?','A generic expresses a relationship between input and output types, such as identity<T>(value:T):T. Constraints limit allowed inputs without discarding their specific types. A generic parameter used only once may not add a useful relationship.','How would you type a key-based lookup?'),
('Medium','How should you answer a behavioral failure question?','Use a specific situation, your responsibility, the action you actually took, and the outcome or lesson. Own your contribution without blaming others or inventing a perfect ending. Describe what changed afterward and what evidence supports the result.','What would you do differently now?'),
('Medium','How should you prepare for an unfamiliar startup?','Read its product and role description, identify the workflows users rely on, and practice a relevant small build. Confirm interview format with the recruiter. Prepare questions about ownership, quality, operations, and constraints rather than memorizing rumored company question lists.','What would you ask about on-call work?'),
('Hard','How do you evaluate a technical tradeoff?','State the requirement, compare alternatives using correctness, complexity, delivery time, and operations, then explain what evidence would change your choice. Name the downside of your selected option and a migration path. An absolute rule usually hides an unstated assumption.','When does your chosen design stop working?'),
('Hard','How do you prepare for a project deep dive?','Trace one request from UI to persistence, explain validation and authorization, and rehearse a failure path. Know the indexes, concurrency behavior, tests, and deployment requirements of your own code. Be able to change one feature during the discussion.','Can you show a failing test and its fix?'),
('Hard','How do you close knowledge gaps without delaying applications forever?','Use a concrete diagnostic: solve a JS exercise, complete a timed UI, build a protected API, and defend a project. Track observed weaknesses and revisit them with retrieval practice. Apply when you can demonstrate the role\'s core skills while continuing targeted practice.','Which evidence shows improvement over the last two weeks?')]
}

NOTES = [
('01-web-html','Web foundations and semantic HTML', 'html-css',[
('Follow a request','A browser resolves a hostname, establishes a connection, and sends an HTTP request. HTTPS adds authenticated encryption. The server sends a status, headers, and a body; the browser parses HTML and discovers other resources. DNS, transport, TLS, and application errors have different diagnostic evidence.','Use the Network panel to distinguish a failed request from a response your code mishandled. Check status and content type before parsing JSON. A 200 response containing an HTML login page can still fail JSON parsing.'),
('Build meaningful documents','Use one clear page title, ordered headings, landmarks, and native links and buttons. A link navigates to a location; a button performs an action. Add alt text that serves the image purpose, and use empty alt for decorative images.','A label is persistent instruction; a placeholder disappears when typing. Connect validation errors to controls and retain the user\'s input. Browser validation does not replace server checks.'),
('Progressive enhancement','Start with useful content and navigation. Add richer interactions without making the core information impossible to reach if JavaScript fails. For an app requiring JavaScript, provide a clear loading and failure experience.','Test keyboard access, zoom, narrow widths, and slow connections. Accessibility is part of correctness, not a last-minute styling task.')], '<form>\n  <label for="email">Email address</label>\n  <input id="email" name="email" type="email" autocomplete="email" required>\n  <button type="submit">Join newsletter</button>\n</form>', 'Build a registration form. Demonstrate labels, error associations, keyboard submission, and preserved input after failure.', 'https://developer.mozilla.org/en-US/docs/Learn_web_development'),
('02-css','CSS layout and responsive interfaces','html-css',[
('Reason about the layout','Use the box model and normal flow before adding positioning. A fixed width can overflow when padding is added under content-box sizing. Apply border-box deliberately, constrain images, and let long text wrap.','Choose flex for distribution along an axis and grid for track alignment. min-width:0 on flex or grid children and minmax(0,1fr) on grid tracks often matter when content would otherwise force overflow.'),
('Debug styles with evidence','Inspect computed styles and the winning declaration. Stacking contexts constrain z-index comparisons. Increasing a number does not allow a descendant to escape its ancestor context.','Avoid unexplained overrides. Use a small spacing and typography system, visible focus outlines, and a layout that survives 200 percent zoom. Respect reduced-motion preferences.'),
('Design responsive behavior','Start with the smallest useful layout and add columns when content has room. Breakpoints should follow the content requirements. Use fluid widths and sensible max-widths rather than targeting a specific device brand.','Reserve media space to reduce shifts. Test unusually long labels and empty states as well as ideal sample data.')], '* { box-sizing: border-box; }\n.cards { display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit,minmax(min(100%,16rem),1fr)); }\nimg { max-width: 100%; height: auto; }\n:focus-visible { outline: 3px solid #174bc9; outline-offset: 3px; }', 'Build a responsive card grid and toolbar. Verify at 320px, 768px, and 200 percent zoom with long content.', 'https://web.dev/learn/css'),
('03-javascript','JavaScript values closures and asynchronous work','javascript',[
('Model values and identities','Objects are compared by identity; two objects with equal-looking properties are distinct. const prevents binding reassignment while nested mutation remains possible. Copy only the parts you change and define how missing, null, zero, and empty string differ in your domain.','Use explicit conversions for user input. Number("") is zero, which is often not an intended amount. Validate the original text and reject nonfinite values.'),
('Use lexical scope','Closures retain access to their defining environment. A callback can retain large data or capture an earlier value. Normal functions get this from how they are called; arrows capture it from their surroundings.','Practice tracing small examples before running them. Explain the invocation, environment, and value rather than memorizing console output.'),
('Control asynchronous operations','Promises describe eventual completion. Awaiting an operation suspends that async function, not the entire runtime. Promise.all preserves input ordering but does not cancel peers after failure.','Debounce user input, cancel obsolete requests, and bound parallel work. Timeouts and retry policies need an explicit contract. Treat a timeout of a write as an uncertain outcome until the server confirms it.')], 'console.log("A");\nsetTimeout(() => console.log("D"), 0);\nPromise.resolve().then(() => console.log("C"));\nconsole.log("B");\n// In a normal browser script: A B C D.', 'Implement debounce, LRU, and a promise pool using the contracts and tests in the JavaScript project.', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide'),
('04-react','React state effects and resilient UI','react',[
('Choose one state owner','Represent each fact in one authoritative place. Derive filtered results and totals during render. Keep drafts local to forms and remote data in a request-aware model. Lift shared state only as far as required.','Stable keys express identity. A changed key can intentionally reset state, while an array index can preserve the wrong row state after reordering.'),
('Make transitions explicit','Functional state updates express a transition from the previous state. A reducer is useful when several values move together. Pure render logic lets React call components without performing hidden side effects.','Do not trigger a payment or mutation simply because a component rendered. User intent belongs in handlers; effects synchronize external systems and clean up subscriptions.'),
('Handle remote state','Show loading, empty, success, and error states separately. Prevent old requests from replacing newer results using cleanup and request identity. Handle HTTP errors explicitly because fetch resolves on many error status codes.','Optimistic writes need rollback or refetch and a conflict policy. Client abort does not prove the server canceled a write. Use versions or mutation ids for correctness.')], 'useEffect(() => {\n  const controller = new AbortController();\n  let current = true;\n  setState({status: "loading"});\n  fetch(`/api/items?q=${encodeURIComponent(query)}`, {signal: controller.signal})\n    .then(r => { if (!r.ok) throw new Error("Request failed"); return r.json(); })\n    .then(data => { if (current) setState({status: "success", data}); })\n    .catch(error => { if (current && error.name !== "AbortError") setState({status: "error", error}); });\n  return () => { current = false; controller.abort(); };\n}, [query]);', 'Explain each state transition in the MERN workspace and demonstrate an API failure without losing the form draft.', 'https://react.dev/learn'),
('05-node-express','Node and Express request architecture','node-express',[
('Separate transport and business rules','The route handles HTTP concerns. A service enforces domain rules, and a repository provides persistence. This separation makes route behavior testable without implying that a fake repository proves database behavior.','Choose one module system per package. State runtime requirements and commit dependency locks. Keep server secrets in process configuration and out of client bundles.'),
('Budget resources','Nonblocking I/O allows useful work while other operations wait. Large synchronous computations still delay unrelated requests. Set request size limits, query bounds, timeouts, and rate limits.','Streams require backpressure and error handling. For CPU work, consider worker threads or background workers after measuring the actual bottleneck.'),
('Control failure paths','Use one error handler that returns safe consistent errors. Express major versions differ for rejected async handlers. Log unexpected errors with correlation ids, while avoiding secrets.','Stop accepting requests during shutdown, finish in-flight work within a deadline, and close connections. Health endpoints should distinguish process health from dependency readiness.')], 'app.use(express.json({limit: "16kb"}));\napp.get("/api/health", (req, res) => res.json({ok: true}));\n// Express 5 forwards a returned rejected promise to error middleware.\napp.use((error, req, res, next) => {\n  if (res.headersSent) return next(error);\n  res.status(500).json({error: "INTERNAL_ERROR"});\n});', 'Add request ids and a structured logger to the reference API. Prove passwords and cookies are redacted.', 'https://nodejs.org/en/learn/getting-started/introduction-to-nodejs'),
('06-mongodb','MongoDB modeling indexes and concurrency','mongodb',[
('Model access and invariants','List the reads, writes, ownership rules, and growth bounds before choosing embedded or referenced data. A document is an atomic write boundary. Keep collections and arrays bounded where the domain allows it.','Mongoose helps express schemas, but a schema alone does not create the right query indexes or authorization rules. Write migrations for data and index changes.'),
('Measure query work','Use explain on representative data. Compare examined keys and documents with returned rows and inspect whether sort work is supported by an index. Indexes improve some reads at a storage and write cost.','For a user-owned timeline, equality on owner followed by an ordered timestamp and id can support a useful compound index. Large skip values deserve a cursor design.'),
('Protect concurrent writes','A read followed by an unconditional update can lose another edit. Include expected version in the update filter and increment version in the same operation. Use conditional stock updates for a single inventory document.','Transactions coordinate multi-document invariants but require an appropriate deployment. External side effects still need idempotency and compensation. The JavaScript event loop cannot enforce consistency across multiple processes.')], 'const result = await tasks.updateOne(\n  {_id: id, owner: userId, version: expectedVersion},\n  {$set: {status: "done"}, $inc: {version: 1}}\n);\nif (result.matchedCount === 0) {\n  // Resolve an owned missing item versus an owned version conflict safely.\n}', 'Run two updates with the same version against MongoDB. Exactly one must match, and the persisted version increases once.', 'https://www.mongodb.com/docs/manual/core/write-operations-atomicity/'),
('07-security','Sessions API security and ownership','security-api',[
('Establish trusted identity','Use a password-specific hash and unique salt. With server sessions, store a digest of a high-entropy session token and expire it. Set HttpOnly, Secure in HTTPS production, and an appropriate SameSite cookie policy.','Logout should revoke the server session as well as clear the browser cookie. Changing password or account status may require broader session revocation.'),
('Authorize every operation','Use the authenticated user id in queries for listing, reading, updating, and deleting. Reject client-owned ownership fields. A public resource id is not permission.','Return a safe missing-resource response to another user instead of revealing whether their id exists. Test cross-user access for every endpoint, not only the UI.'),
('Constrain input and side effects','Validate scalar types and allowed values. Build explicit writes rather than spreading untrusted input. Restrict URL schemes and avoid fetching user-supplied URLs unless necessary.','Cookie-authenticated writes need CSRF defenses. The reference workspace uses same-origin deployment, a strict Origin check on writes, JSON bodies, and SameSite cookies. If deployment becomes cross-origin, revisit the whole contract.')], 'const task = await tasks.findOne({_id: requestedId, owner: req.user.id});\nif (!task) return res.status(404).json({error: "NOT_FOUND"});\n// Never take owner from req.body or a user-controlled header.', 'Use two accounts and verify that lists, updates, and deletes do not cross ownership boundaries.', 'https://cheatsheetseries.owasp.org/'),
('08-testing','Testing debugging and delivery','testing-tooling',[
('Test observable contracts','Write expected results from the specification, including boundaries, duplicates, invalid values, and failures. Avoid computing expected output with the same algorithm being tested.','A fake database is appropriate for route contracts. Real database tests are necessary for indexes and atomic predicates. Browser tests are necessary for focus and realistic interaction.'),
('Debug systematically','Reproduce the issue, reduce it to a small case, inspect the relevant layer, and write a regression test where it adds value. Change one hypothesis at a time.','Use network logs for request failures, browser traces for rendering, and database explain output for query work. A rewrite without diagnosis may preserve the underlying failure.'),
('Make setup repeatable','Commit lockfiles, provide env examples without secrets, document database requirements, and run builds in CI. State which checks passed and which environments were unavailable.','Tests should fail when important behavior breaks. A project with only screenshots or syntax checks has not established authorization, persistence, or recovery correctness.')], 'import {test} from "node:test";\nimport assert from "node:assert/strict";\ntest("a stale edit cannot overwrite the newer task", async () => {\n  // Arrange two requests at the same expected version.\n  // Assert one succeeds, one conflicts, and data changes only once.\n});', 'Add a regression test for a bug you can reproduce, then verify that reverting the fix makes the test fail.', 'https://testing-library.com/docs/react-testing-library/intro/'),
('09-design','System design for product engineers','system-design',[
('Clarify the contract','State the core use cases, scale estimates, latency target, consistency requirement, and operational constraints. Label estimates as assumptions. Choose a simple initial design and identify the first bottleneck.','For a URL shortener, ask about custom aliases, expiration, abuse, and analytics. For a feed, ask about ordering, private content, pagination, and freshness.'),
('Design for partial failure','Use timeouts, bounded retries, and idempotency for operations that can repeat. Queues usually provide at-least-once processing under common configurations, so consumers must tolerate duplicates.','An outbox connects a database write to eventual event publication, but consumers still deduplicate. Monitor backlog and provide a failure-handling path.'),
('Explain evolution','Caches need correct key scope and freshness rules. Replication changes failure and consistency behavior. Sharding and extra services add operational work.','Discuss a measurable trigger for each additional component. If no requirement needs a distributed design, a well-structured service and database may be the better starting point.')], '// An idempotent write needs durable state, not only a process-local Set.\n// unique index: {owner: 1, operationId: 1}\n// Persist operation result with the business change under the chosen atomic boundary.', 'Draw a notification design, trace a crash between save and publish, and explain how the request eventually reaches a user without duplicate business effects.', 'https://www.mongodb.com/docs/manual/core/transactions/'),
('10-typescript','TypeScript and explicit domain states','typescript-career',[
('Represent valid states','Use discriminated unions when fields depend on a state. A success variant carries data; an error variant carries a message. This reduces impossible combinations compared with several independent booleans.','Prefer unknown for external data until validated. Static types describe your assumptions; runtime checks establish whether incoming data satisfies them.'),
('Keep relationships in types','Generics connect input and output types without discarding specifics. Constraints express the capabilities required. Narrow values with checks rather than using broad type assertions.','Use strict compiler settings for a new typed project. Avoid any at API boundaries, and do not claim that a TypeScript migration makes an unvalidated server secure.'),
('Practice migration','Migrate a small service or state reducer first. Keep runtime behavior stable, add precise types, and retain tests. Typed libraries can still deliver invalid data at runtime.','Explain where types help and where they do not: authorization, network failure, concurrency, and database constraints remain runtime concerns.')], 'type Remote<T> =\n  | {status: "idle"}\n  | {status: "loading"}\n  | {status: "success"; data: T}\n  | {status: "error"; message: string};\nfunction summary(state: Remote<string[]>) {\n  return state.status === "success" ? state.data.length : 0;\n}', 'Port one API response parser and one React reducer to TypeScript with strict checking and no unchecked assertion of external data.', 'https://www.typescriptlang.org/docs/')
]

SCENARIOS = [
('SC01','React','Search results jump backward while typing','Throttle the network and type three queries quickly. Record each request id and response time.','An earlier request completes after a later request and overwrites the visible state.','Abort obsolete requests and guard completion with a request generation. Clearing the query also invalidates work.','Resolve mocked requests in reverse order; the final UI must match the newest query.','Debounce reduces requests but does not guarantee ordering.'),
('SC02','React','A timer always sees the first counter value','Log the render value and callback value and inspect effect dependencies.','A callback captured a prior render snapshot.','Use a functional state update when only the previous value is needed, or resubscribe with correct dependencies. Use a ref only when a current mutable value is truly required.','Advance timers after several increments and verify current behavior and cleanup.','Suppressing the dependency warning hides the stale closure.'),
('SC03','React','Editing a sorted list changes the wrong row','Type into a row, then sort or insert at the front.','Index keys give the row component a different domain item while keeping state.','Key by stable item id and decide whether edits belong in row-local drafts or a keyed parent model.','Edit one id and reorder; the draft remains attached to that id.','Random keys force remounts and lose all drafts.'),
('SC04','React','An optimistic task update overwrites a newer edit','Send two edits from separate tabs at the same version.','The server accepts writes without a concurrency condition.','Require expectedVersion, update atomically, and return an owned conflict. On conflict, refresh and let the user reconcile.','Against real MongoDB, run concurrent updates and assert exactly one success.','The UI alone cannot serialize other devices or processes.'),
('SC05','Browser','A form looks fine but cannot be completed with a keyboard','Use Tab and Shift+Tab without the mouse. Inspect role and label relationships.','Clickable divs, missing labels, or focus loss break interaction.','Replace controls with native buttons and inputs, restore focus after dialogs, and associate errors with controls.','Complete the flow with keyboard and inspect accessible names.','Adding tabindex alone does not supply activation or semantics.'),
('SC06','CSS','A card pushes a grid wider than the viewport','Test a long unbroken title and inspect the overflowing box.','An intrinsic minimum or fixed width prevents shrinking.','Use minmax(0,1fr), min-width:0, wrapping, and constrained media where the content contract permits.','Check 320px width and 200 percent zoom with long input.','Hiding overflow can conceal required information.'),
('SC07','Node','All requests slow down during report generation','Correlate CPU profiles and event-loop delay with report requests.','Synchronous CPU work blocks the request-handling thread.','Move expensive work to a worker or job queue, bound workload, and report asynchronous progress.','Load test with concurrent small requests and a report; compare tail latency.','Making the function async does not offload computation.'),
('SC08','Node','Memory grows on every page visit','Repeat the flow, force comparable heap snapshots, and inspect retaining paths.','A long-lived listener or cache retains per-request or per-page data.','Unsubscribe, clear timers, or bound and evict cache entries; verify the actual retaining path.','Repeat the workload after the fix and compare retained objects.','A single lower heap reading does not prove leak removal.'),
('SC09','API','User A can delete User B\'s task by changing an id','Create two users and attempt the delete as A using B\'s id.','The database filter lacks authenticated ownership.','Include owner in every item and list query. Ignore client ownership fields and return a safe missing response.','Read, update, delete, and list isolation tests all preserve B\'s data.','Hiding ids or changing to UUIDs does not authorize access.'),
('SC10','API','Cross-site form submission changes account settings','Inspect cookie settings, content type, Origin checks, and CSRF policy.','Cookie authentication is accepted without a coherent write-origin defense.','Use a defined CSRF strategy, appropriate SameSite cookies, and same-origin enforcement for the reference deployment. Reassess cross-origin requirements.','Send missing and foreign Origin writes; both must fail under the chosen contract.','CORS response restrictions are not a complete CSRF policy.'),
('SC11','MongoDB','Two requests both purchase the last item','Run two overlapping reservations against stock=1.','Each request reads stock before an unconditional decrement.','Use one atomic predicate with stock >= requested amount and decrement in that write. Coordinate reservation expiration and payment separately.','At most one reservation succeeds; stock remains nonnegative.','A process-local mutex does not protect multiple instances.'),
('SC12','MongoDB','A uniqueness check passes but duplicate registration fails','Send simultaneous registrations and inspect database index errors.','Both prechecks pass before either inserts.','Enforce the unique index and map duplicate-key errors to a safe conflict response. Prechecks may improve feedback but are not the invariant.','Exactly one insert succeeds under concurrency.','Removing the index to avoid E11000 removes protection.'),
('SC13','MongoDB','The feed skips or repeats items during new inserts','Compare offset pages while inserting earlier records.','Offset boundaries shift and timestamp ties are not uniquely ordered.','Use a cursor containing the last stable sort tuple, with an id tie-breaker and validated scope.','Insert between page requests and verify stable traversal of the documented contract.','Cursor pagination is not automatically a snapshot of all data.'),
('SC14','MongoDB','A small database query becomes slow at scale','Run explain on representative cardinality and compare examined versus returned records.','The query scans too much or sorts outside a useful index.','Design an index for real equality, sort, and range requirements; bound responses and measure before and after.','Document query plans and latency under the same dataset.','A faster run on ten sample rows is weak evidence.'),
('SC15','Security','A JWT includes a password hash','Decode a test token and inspect only safe nonproduction data.','Sensitive data was put in a readable signed payload.','Remove sensitive claims, rotate affected credentials or sessions as required, and restrict claims to the minimum needed.','Assert serialized tokens and API responses never contain secret fields.','Signing a payload does not encrypt it.'),
('SC16','Security','A bookmark preview reads an internal admin endpoint','Inspect the server fetch destination, redirects, and resolved addresses.','The application performs unrestricted server-side URL fetching.','Avoid server fetching in a simple bookmark project. If previews are required, isolate egress and validate each destination and redirect.','Reject internal destinations in a controlled test environment.','Checking only that the string begins with https is insufficient.'),
('SC17','Delivery','The payment provider retries and a user is charged twice','Correlate operation ids, webhook ids, and durable records.','The handler assumes one delivery or retries a non-idempotent operation.','Use provider-supported idempotency and a durable unique operation record with the chosen atomic boundary. Verify webhook signatures.','Replaying an event does not repeat the business effect.','An in-memory deduplication map disappears on restart.'),
('SC18','Delivery','The task was saved but its notification was lost','Trace a crash immediately after the database commit and before queue publish.','Two separate writes do not share a durable handoff.','Use an outbox persisted with the business change and a retrying publisher. Make consumers idempotent.','Crash at each boundary; the event eventually publishes without duplicate business effects.','An outbox does not guarantee exactly-once transport.'),
('SC19','Testing','Tests pass but the browser receives HTML for an API route','Serve the built app and inspect content type on the API response.','An SPA fallback or proxy is matching an API path incorrectly.','Mount API routes first, return API 404s for unknown API paths, and restrict the SPA fallback to page navigation.','Test an unknown API path and a client route against the production server.','Development proxy success does not prove production routing.'),
('SC20','Tooling','A deployment installs different package versions','Compare lockfile, manifest, runtime, and install command.','The build resolves floating versions or ignores the lockfile.','Commit the dependency lock, use npm ci, and declare compatible runtime versions. Update deliberately through a tested change.','A clean CI install produces the same resolved graph.','A lockfile does not validate all environments or dependency safety.'),
('SC21','Operations','Rate limits disappear when another instance serves the request','Route the same caller to multiple instances and compare counters.','Counters exist separately in process memory.','Use a shared limiter or gateway for distributed enforcement, with explicit outage and key policies.','A caller receives one global budget across instances.','A trusted proxy must be configured before using forwarded IPs.'),
('SC22','Operations','Shutdown drops active requests','Send a slow request and terminate the server in a controlled environment.','The process exits before requests and connections drain.','Stop accepting connections, drain within a deadline, close dependencies, and handle stuck sockets deliberately.','The slow request finishes or follows a documented bounded failure policy.','Waiting indefinitely can block deployment forever.'),
('SC23','TypeScript','A typed API returns a string where a number is expected','Inspect the incoming payload before an assertion or cast.','Type annotations were treated as runtime validation.','Parse unknown input at the boundary and reject invalid types. Preserve static types after successful validation.','An incorrect payload produces a validation error rather than silent arithmetic coercion.','Using as number changes no runtime value.'),
('SC24','Career','The interviewer asks for a tradeoff you cannot explain','Trace a real feature and identify the requirement that led to the design.','The project was copied without understanding its constraints.','Implement a small extension yourself, document an alternative, and measure or test the deciding behavior.','Explain one invariant, demonstrate a failure path, and justify a different choice under a changed requirement.','Memorized slogans are not evidence of design judgment.')
]

MACHINE = [
('MC01','Easy',45,'Accessible accordion','html-css','Multiple sections can open; buttons expose aria-expanded and controls ids.','None expanded, one expanded, multiple expanded, keyboard activation.','Use a Set of section ids; render state through native buttons; keep content mounted if its state must persist.'),
('MC02','Easy',45,'Todo with undo','javascript','Create, complete, filter, delete, and undo the most recent delete; ids are stable.','Whitespace title, duplicate titles, delete under active filter, undo twice.','Use normalized ids and a pure reducer; keep one bounded deleted item for the stated contract.'),
('MC03','Medium',60,'Debounced search','react','Search after 300ms quiet time; render loading, empty, error; latest query wins.','Out-of-order responses, clearing query, unmount, retry after failure.','Debounce input and independently guard request identity; abort on cleanup; preserve query on retry.'),
('MC04','Medium',75,'Sortable paginated table','react','Sort full dataset by name or numeric amount; page after sorting; preserve stable ids.','Ties, zero, negative numbers, last page after deleting, empty data.','Keep sort and page as state; derive sorted and sliced rows; reset invalid pages; use aria-sort.'),
('MC05','Medium',60,'Modal with focus return','html-css','Open from a trigger, accessible title, Escape close, focus return, background interaction blocked.','Repeated open and close, trigger removed, long dialog, keyboard-only use.','Use native dialog and showModal; remember the invoking element; select a useful initial focus target.'),
('MC06','Medium',75,'Shopping cart','react','Add items, change quantities 1..99, remove, show integer-cent totals, prevent duplicate submit.','Stock changes, invalid quantity, empty cart, zero-price item.','Key lines by product id; derive totals; server must validate actual price and stock on checkout.'),
('MC07','Medium',90,'Nested file explorer','react','Expand folders, select a file, rename and create unique sibling names.','Deep nesting, empty folder, duplicate names, rename root policy.','Use ids independent of names; recurse for presentation and keep expanded ids separately.'),
('MC08','Medium',75,'Multi-step form','react','Three steps, per-step validation, back preserves drafts, final submit once.','Server error, navigating back, missing fields, keyboard submission.','One authoritative draft and explicit step state; validate transitions and retain data on errors.'),
('MC09','Hard',90,'Keyboard autocomplete','react','Arrow navigation, Enter selection, Escape collapse, combobox semantics, latest async query wins.','No matches, IME composition, changed list during selection, blur before click.','Keep active index valid as results change; use aria-activedescendant and pointer handling without stealing input focus.'),
('MC10','Hard',90,'Kanban with conflict recovery','react','Move tasks among columns using buttons; persist versioned writes; recover on conflict.','Two tabs, failed write, delete while moving, empty column.','Separate local pending state from server state; expected version belongs to each mutation; refetch after conflict.'),
('MC11','Hard',75,'Promise pool','javascript','Run at most k task factories, ordered results, explicit failure policy, invalid limit rejected.','Empty tasks, rejection, k larger than input, synchronous throw.','Workers claim indexes and await one task each; store outcome by original index; account for tasks already running.'),
('MC12','Hard',75,'LRU with TTL extension','javascript','Constant-average-time get and set, capacity eviction, optional injected clock for TTL.','Existing key update, stored undefined, capacity=1, invalid capacity, expiry boundary.','Use Map order for recency and distinguish has from get; check expiry lazily and bound storage.'),
('MC13','Medium',90,'Protected CRUD API','node-express','Validate input, authenticate, scope reads and writes by owner, bound list size.','Unauthenticated access, cross-user ids, unknown properties, malformed body.','Build filters from validated fields and trusted identity; use one safe error mapper and route integration tests.'),
('MC14','Hard',120,'Inventory reservation API','mongodb','Reserve stock atomically, operation id deduplication, expiration policy, no negative stock.','Two last-item requests, repeated operation id, invalid quantity, expiration races.','Choose an atomic data model or transaction; persist deduplication with the business effect; test against real MongoDB.'),
('MC15','Hard',90,'Notification center','react','Unread count, mark read, filter, pagination, retry errors, accessible announcements.','Duplicate pages, repeated mark-read, newest item during paging, offline.','Normalize records by id; treat mark-read as idempotent; keep cursor and request state explicit.'),
('MC16','Hard',120,'Expense dashboard','react','Add dated integer-cent expenses, filter category, total authoritative data, authenticated persistence.','Invalid decimal input, date overflow, empty filter, cross-user access.','Parse money exactly, use validated calendar dates, derive totals consistently, and test ownership and amount boundaries.')
]

RESOURCES = [
('Web fundamentals','MDN learning curriculum','https://developer.mozilla.org/en-US/docs/Learn_web_development','Beginner','Free','Start with core modules; recreate each exercise without looking.','verified'),
('HTML CSS JS','web.dev courses','https://web.dev/learn','Beginner to advanced','Free','Use HTML, CSS, forms, accessibility, and performance tracks.','verified'),
('JavaScript','JavaScript.info','https://javascript.info/','Beginner to advanced','Free web; optional paid ebooks','Work through language, DOM, and asynchronous exercises.','verified'),
('Full stack','Full Stack Open','https://fullstackopen.com/en/','Intermediate','Free','Complete React and Node exercises after JavaScript fundamentals.','verified'),
('Full stack','The Odin Project JavaScript path','https://www.theodinproject.com/paths/full-stack-javascript','Beginner to intermediate','Free','Use project assignments for independent builds.','verified'),
('React','React Learn','https://react.dev/learn','Beginner to advanced','Free','Build the examples and explain state transitions aloud.','verified'),
('React','You Might Not Need an Effect','https://react.dev/learn/you-might-not-need-an-effect','Intermediate','Free','Review each effect in your project and justify its external synchronization.','verified'),
('Node','Node Learn','https://nodejs.org/en/learn/getting-started/introduction-to-nodejs','Beginner to advanced','Free','Study runtime behavior alongside a small API.','verified'),
('Express','Express installation and guides','https://expressjs.com/en/starter/installing.html','Beginner to intermediate','Free','Check the installed major version before following older tutorials.','verified'),
('MongoDB','MongoDB manual getting started','https://www.mongodb.com/docs/manual/tutorial/getting-started/','Beginner','Free docs; hosted usage may cost','Practice CRUD on a local or test database.','verified'),
('MongoDB','Atomicity and transactions','https://www.mongodb.com/docs/manual/core/write-operations-atomicity/','Advanced','Free','Test concurrent writes rather than relying on a diagram.','verified'),
('Mongoose','Mongoose schemas guide','https://mongoosejs.com/docs/guide.html','Intermediate','Free','Compare validation, indexes, and update behavior.','verified'),
('TypeScript','TypeScript handbook','https://www.typescriptlang.org/docs/','Beginner to advanced','Free','Port one reducer and validate external data at runtime.','verified'),
('Testing','React Testing Library','https://testing-library.com/docs/react-testing-library/intro/','Intermediate','Free','Test visible outcomes through accessible roles.','verified'),
('Testing','Playwright documentation','https://playwright.dev/docs/intro','Intermediate','Free','Test the built app and keyboard workflows.','verified'),
('Build tools','Vite guide','https://vite.dev/guide/','Beginner to intermediate','Free','Understand development proxy versus production hosting.','verified'),
('Security','OWASP Cheat Sheet Series','https://cheatsheetseries.owasp.org/','Intermediate to advanced','Free','Use targeted authentication, session, CSRF, and input-validation references.','verified'),
('Accessibility','WAI tutorials','https://www.w3.org/WAI/tutorials/','Beginner to advanced','Free','Review forms, images, tables, and page structure.','verified'),
('Git','Pro Git book','https://git-scm.com/book/en/v2','Beginner to advanced','Free','Practice branches, conflict resolution, and recovery in a sandbox repository.','verified'),
('API contracts','OpenAPI specification','https://spec.openapis.org/oas/latest.html','Intermediate','Free','Write and validate a small API contract.','verified'),
('Practice','freeCodeCamp','https://www.freecodecamp.org/learn/','Beginner','Free','Supplement notes with independent exercises; verify current course tracks.','partial: page reached but content extraction unavailable'),
('DSA practice','LeetCode study plans','https://leetcode.com/studyplan/','Intermediate','Mixed free and paid','Practice patterns and explain complexity; avoid memorizing company tags as predictions.','verified'),
('Interview practice','GreatFrontEnd','https://www.greatfrontend.com/','Intermediate to advanced','Mixed free and paid','Optional UI and frontend interview practice; repository exercises remain free.','verified'),
('Browser debugging','Chrome DevTools','https://developer.chrome.com/docs/devtools/','Intermediate','Free','Capture traces and network evidence while debugging.','retrieval failed; check directly in browser'),
('Deployment','Docker getting started','https://docs.docker.com/get-started/','Intermediate','Free docs; service plans vary','Run the sample MongoDB stack and learn volume persistence.','verified'),
('Company','Amazon how we hire','https://www.amazon.jobs/content/en/how-we-hire','All','Free','Confirm the role format and prepare evidence-based behavioral stories.','verified'),
('Company','Google hiring process','https://www.google.com/about/careers/applications/how-we-hire/','All','Free','Review official process and ask the recruiter for your role format.','verified'),
('Company','Microsoft technical interviewing','https://careers.microsoft.com/v2/global/en/hiring-tips/technical-interviewing','All','Free','Use official preparation guidance; practice clarification and reasoning.','verified')
]

def main():
    bank=[]
    qnum=0
    for topic, questions in QUESTIONS.items():
        parts=[f'# {topic.replace("-", " ").title()} interview questions', '\n[Handbook](../README.md) | [All question ids](index.md)', '\nDifficulty is an editorial learning classification. Questions are original practice, not a company question leak. Cover the answer before attempting recall.']
        for difficulty,prompt,answer,followup in questions:
            qnum+=1; qid=f'Q{qnum:03}'
            bank.append(dict(id=qid,topic=topic,difficulty=difficulty,question=prompt,answer=answer,followup=followup))
            parts += [f'\n## {qid} {difficulty} - {prompt}', f'\n<details>\n<summary>Answer and follow-up</summary>\n\n{answer}\n\n**Follow-up:** {followup}\n\n</details>']
        write(f'interview-handbook/questions/{topic}.md','\n'.join(parts))
    write('interview-handbook/questions/index.md', '# Question index\n\nAttempt each question without the answer, then explain the follow-up. Score 0 = cannot explain, 1 = definition only, 2 = correct with example, 3 = correct with tradeoff and failure case. Revisit scores below 2 after 1, 3, 7, and 14 days.\n\n| ID | Difficulty | Topic | Question |\n| --- | --- | --- | --- |\n'+'\n'.join(f'| {q["id"]} | {q["difficulty"]} | {q["topic"]} | [{q["question"]}]({q["topic"]}.md#{q["id"].lower()}-{q["difficulty"].lower()}---'+q['question'].lower().replace('?','').replace('.','').replace(' + ','--').replace(' ','-')+') |' for q in bank))
    # Stable links to files; GitHub heading normalization is not used as a generated contract.
    write('interview-handbook/questions/index.md', '# Question index\n\nScore 0 = cannot explain, 1 = definition only, 2 = correct with example, 3 = correct with tradeoff and failure case. Revisit weak answers after 1, 3, 7, and 14 days. Difficulty is a learning classification.\n\n| ID | Difficulty | Topic | Question |\n| --- | --- | --- | --- |\n'+'\n'.join(f'| {q["id"]} | {q["difficulty"]} | {q["topic"]} | [{q["question"]}]({q["topic"]}.md) |' for q in bank))
    for slug,title,topic,sections,code,exercise,source in NOTES:
        text=f'# {title}\n\n[Handbook](../README.md) | [Practice questions](../questions/{topic}.md)\n\nRead this guide, run the example, and demonstrate the exercise before moving on. These notes supplement the original classroom modules.\n'
        for heading,p1,p2 in sections: text+=f'\n## {heading}\n\n{p1}\n\n{p2}\n'
        lang='html' if slug=='01-web-html' else 'css' if slug=='02-css' else 'ts' if slug=='10-typescript' else 'jsx' if slug=='04-react' else 'js'
        text+=f'\n## Worked example\n\n```{lang}\n{code}\n```\n\n## Demonstrate understanding\n\n{exercise}\n\n## Reference\n\n[Primary learning reference]({source}). Prefer the documentation matching the version you install.\n'
        write(f'interview-handbook/notes/{slug}.md',text)
    scenarios=['# Scenario practice\n\n[Handbook](../README.md)\n\nFor each case, explain the symptom, gather evidence, state a hypothesis, propose a fix, and identify a regression check. Each is an original practice case.']
    for sid,topic,symptom,evidence,cause,fix,test,pitfall in SCENARIOS:
        scenarios += [f'\n## {sid} {topic} - {symptom}', f'\n**Evidence to collect:** {evidence}\n\n<details>\n<summary>Diagnosis and answer</summary>\n\n**Likely cause:** {cause}\n\n**Fix:** {fix}\n\n**Verification:** {test}\n\n**Common mistake:** {pitfall}\n\n</details>']
    write('interview-handbook/scenarios/README.md','\n'.join(scenarios))
    machine=['# Machine coding practice\n\n[Handbook](../README.md) | [Runnable sources](../../projects/interview-ready/README.md)\n\nAll times are suggested practice limits, not company promises. Read requirements, start a timer, and build before opening the solution approach. You may use the reference projects after the attempt.\n\n| ID | Level | Minutes | Exercise |\n| --- | --- | --- | --- |']
    for mid,level,minutes,title,topic,req,edge,approach in MACHINE:
        slug=title.lower().replace(' ','-')
        machine.append(f'| {mid} | {level} | {minutes} | [{title}]({mid.lower()}-{slug}.md) |')
        write(f'interview-handbook/machine-coding/{mid.lower()}-{slug}.md',f'''# {mid} {title}

[Exercise index](README.md) | [Scoring rubric](rubric.md)

Level: {level}. Suggested time: {minutes} minutes. Topic: {topic}.

## Required behavior

{req}

## Acceptance checks

{edge} The core interaction must work with a keyboard. Show empty and failure states when applicable. Explain the data contract and what remains incomplete.

## Deliverables

Provide runnable source, setup instructions, a short state or API design explanation, and evidence for the acceptance checks. Avoid spending the first half of the round on styling.

## Suggested time budget

Use roughly 10 percent for clarification and state design, 55 percent for a complete core flow, 20 percent for boundaries and failure recovery, and 15 percent for a demo and explanation. If time runs short, retain correctness and clearly state omitted extensions.

<details>
<summary>Solution approach after your attempt</summary>

{approach}

Explain the main invariant and one alternative. Apply the shared rubric rather than treating a visual match as sufficient proof.

</details>
''')
    write('interview-handbook/machine-coding/README.md','\n'.join(machine))
    write('interview-handbook/machine-coding/rubric.md','''# Machine coding review rubric

| Dimension | Points | Evidence |
| --- | ---: | --- |
| Required behavior | 30 | Demonstrate each requested interaction and correct resulting state |
| Boundaries and failure recovery | 20 | Invalid input, empty results, async errors, and race behavior where applicable |
| State and API design | 15 | One owner per fact, stable ids, clear transitions, bounded work |
| Accessibility | 15 | Semantic controls, labels, focus, keyboard operation, error announcements |
| Verification | 10 | Relevant behavioral checks with explicit expected outcomes |
| Explanation | 10 | Invariant, tradeoff, complexity, omissions, and next steps |

Suggested readiness target: 75/100 with no missing core flow or cross-user authorization failure. This is a self-assessment target, not a hiring cutoff. Record the evidence, not just a number. Repeat one weak exercise after three days.
''')
    resources='# Curated external learning resources\n\nReviewed on 2026-10-08. These links are selected learning options, not an exhaustive ranking. Availability, pricing, and hiring processes can change. External content keeps its own license; this repository links to it and does not redistribute course PDFs.\n\n| Topic | Resource | Level | Access | How to use it |\n| --- | --- | --- | --- | --- |\n'
    resources+='\n'.join(f'| {topic} | [{name}]({url}) | {level} | {cost} | {use} |' for topic,name,url,level,cost,use,status in RESOURCES)
    write('interview-handbook/resources/README.md',resources)
    write('interview-handbook/resources/catalog.json',json.dumps([dict(topic=t,name=n,url=u,level=l,access=c,use=use,lastReviewed='2026-10-08',verification=s) for t,n,u,l,c,use,s in RESOURCES],indent=2))
    write('interview-handbook/data/question-bank.json',json.dumps(bank,indent=2))
    write('interview-handbook/data/study-data.json',json.dumps(dict(notes=[dict(slug=n[0],title=n[1],topic=n[2],sections=n[3],code=n[4],exercise=n[5],source=n[6]) for n in NOTES],questions=bank,scenarios=[dict(zip(['id','topic','symptom','evidence','cause','fix','test','pitfall'],s)) for s in SCENARIOS],machine=[dict(zip(['id','level','minutes','title','topic','requirements','edges','approach'],s)) for s in MACHINE]),indent=2))
    for name,headers,rows in [
        ('questions',['ID','Topic','Difficulty','Question','Score 0 to 3','Status','Next review','Notes'],[[q['id'],q['topic'],q['difficulty'],q['question'],'','Not started','',''] for q in bank]),
        ('machine-coding',['ID','Difficulty','Minutes','Exercise','Score out of 100','Status','Attempt date','Evidence'],[[s[0],s[1],s[2],s[3],'','Not started','',''] for s in MACHINE])]:
        p=BASE/'downloads'/f'{name}.csv';p.parent.mkdir(parents=True,exist_ok=True)
        with p.open('w',newline='',encoding='utf-8-sig') as f:
            writer=csv.writer(f);writer.writerow(headers);writer.writerows(rows)
    print(f'Generated {len(NOTES)} notes, {len(bank)} questions, {len(SCENARIOS)} scenarios, {len(MACHINE)} machine coding exercises, and {len(RESOURCES)} resources.')

if __name__=='__main__': main()
