"""Small original references. They link to explanation, not replace it."""
SHEETS={
'javascript':('JavaScript','javascript',"const next = {...item, tags:[...item.tags, 'new']};\nconst selected = rows.filter(row => row.active);\nconst names = selected.map(row => row.name);\nconst missingOnly = value ?? fallback;",'const does not freeze objects. Spread is shallow. Prefer explicit parsing and identity rules.'),
'typescript':('TypeScript','typescript',"type Result<T> = {ok:true; value:T} | {ok:false; error:string};\nfunction read<T>(result:Result<T>) {\n  return result.ok ? result.value : result.error;\n}", 'unknown inputs need runtime checks. as is an assertion, not a validator.'),
'react':('React','react',"const [count,setCount] = useState(0);\nsetCount(previous => previous + 1);\n// Derive values during render.\n// Effects connect to external systems; return cleanup.", 'Use stable keys, preserve form drafts, and keep commands out of rendering.'),
'node':('Node.js','nodejs',"import {pipeline} from 'node:stream/promises';\nawait pipeline(sourceStream, destinationStream);\n// Match package type to ESM/CommonJS.\n// Close handles and define a shutdown deadline.", 'async does not move CPU work off the thread. Bound I/O and worker concurrency.'),
'express':('Express','express',"app.use(express.json({limit:'16kb'}));\napp.patch('/api/items/:id', requireSession, async (req,res) => {\n  const result = await service.update(req.user.id, req.params.id, validate(req.body));\n  res.json(result);\n});", 'Fragment requires the named dependencies. Keep API routes before fallback; Express 5 rejected returned Promises reach error handling.'),
'mongodb':('MongoDB','mongodb',"db.tasks.find({owner:'a'}, {title:1}).limit(20);\ndb.tasks.updateOne({_id:'demo',owner:'a',version:0},\n  {$set:{status:'done'},$inc:{version:1}});", 'Use a disposable database. A unique index and an atomic predicate establish different invariants.'),
'mongoose':('Mongoose','mongoose',"schema.index({owner:1,url:1},{unique:true});\n// Verify the database index.\nconst rows = await Model.find({owner}).lean();\n// Lean returns plain values; check hydration needs.", 'unique is an index declaration. Update validators and hooks depend on the method used.'),
'sql':('SQL','sql',"SELECT owner_id, SUM(amount_cents)\nFROM expenses\nGROUP BY owner_id;\n-- Use driver parameters for values, not interpolation.", 'Requires the declared table. Check engine syntax and isolation. One-to-many joins can multiply totals.'),
'git':('Git','git',"git status --short\ngit diff\ngit diff --cached\ngit log --oneline -5", 'Inspect states before changing history. Revert adds a compensating commit; reset may alter local work.'),
'docker':('Docker','devops',"docker compose ps\ndocker compose logs --tail=30\ndocker image ls\ndocker volume ls", 'Run within the intended environment. Containers, images, and data volumes have different lifetimes.'),
'rest-apis':('REST APIs','api',"GET /items?limit=20&cursor=...\nPOST /items\nPATCH /items/:id\nDELETE /items/:id", 'Define ownership, supported fields, stable pagination, safe errors, and retry/idempotency behavior.'),
'http':('HTTP','foundations',"200 success representation\n201 created resource\n400 invalid request; 401 credentials required\n403 forbidden; 404 missing/unavailable\n409 conflict; 429 rate limited; 500 unexpected server failure", 'Status, content type, body, and headers form one response contract. Fetch does not reject merely because status is 404.'),
'authentication':('Authentication','security',"Trusted credential -> verified identity\nIdentity + permission predicate -> authorized operation\nExpiration + revocation -> session lifetime\nSafe public response -> no credential disclosure", 'Signed JWT payloads are readable. HttpOnly and CORS do not replace CSRF defenses or ownership.'),
'css':('CSS','css',"* { box-sizing: border-box; }\n.grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); }\n.child { min-width:0; overflow-wrap:anywhere; }\n:focus-visible { outline:3px solid #ce6a16; }", 'Inspect cascade stage, intrinsic size, and stacking context before adding specificity or z-index.'),
'regex':('Regular expressions','javascript',"const safeId = /^[a-f0-9]{24}$/i.test(input);\nconst twoDecimals = /^\\d+(?:\\.\\d{1,2})?$/.test(input);\n// Anchors check the whole string.\n// State and Unicode behavior depend on flags.", 'Limit input size and avoid catastrophic backtracking patterns. A format match does not prove domain validity.'),
'terminal':('Terminal','devops',"pwd\nls\nnode --version\npython --version\n# Quote a path containing spaces.", 'These examples use a POSIX shell. PowerShell equivalents include Get-Location and Get-ChildItem. A terminal hosts a shell; it is not itself a programming language.'),
'linux':('Linux','devops',"ps -ef\ndf -h\nls -l\n# Inspect service logs using the deployment service manager.", 'Understand owner/group/mode, process lifetime, mounts, and networking before changing permissions. Avoid broad recursive permission changes.')}
def build(write):
    index='# Quick references\n\nThese concise references are reminders, not substitutes for the linked guides. Fragments require surrounding variables or services as stated.\n\n'
    for id,(title,guide,code,pitfall) in SHEETS.items():
        index+=f'- [{title}]({id}.md)\n'
        text=f'# {title} quick reference\n\nPriority: P0/P1 for core use; specialized operations remain in the linked guide.\n\n[Explanation and prerequisites](../topics/{guide}.md) · [All quick references](README.md)\n\n## Common contract\n\n```text\n{code}\n```\n\n## Remember\n\n{pitfall}\n\n## Verify before applying\n\nCheck the installed runtime, required surrounding values, permitted input, expected outcome, and failure behavior. Practice one changed input rather than copying a fragment without its contract.\n\nLast verified: 2026-10-08; see the guide for publisher sources and execution limits.\n'
        write(f'knowledge-base/cheatsheets/{id}.md',text)
    write('knowledge-base/cheatsheets/README.md',index)
