"""Authored routes and project briefs; implementation status is explicit."""
PATHS={
'80-20-mern-developer':('80/20 MERN Developer','Build useful features quickly, then revisit weak concepts.',['foundations','html','css','javascript','async','browser','react','nodejs','api','express','mongodb','security','testing','git'],'Complete the beginner lab, then change one MERN workspace feature.','Explain and test a complete authenticated write, one failure recovery, and one persisted invariant.'),
'complete-mern-developer':('Complete MERN Developer','Explore the whole mapped landscape; this route is a goal, not a completeness certification.',['foundations','html','css','javascript','async','browser','typescript','git','react','state-management','nextjs','nodejs','api','express','mongodb','mongoose','sql','redis','security','realtime','testing','devops','cloud','engineering','system-design'],'Use every area guide and identify reference-only concepts for deeper independent practice.','Finish core projects and produce a gap list with evidence for specialized concepts instead of checking every heading complete.'),
'frontend-developer':('Frontend Developer','Build accessible, responsive, recoverable browser experiences.',['foundations','html','css','javascript','browser','async','typescript','react','state-management','testing','git'],'Build the quiz and weather lab, then timed search, table, and modal exercises.','Demonstrate keyboard use, mobile layout, async race recovery, stable identity, and visible error handling.'),
'react-developer':('React Developer','Reason precisely about component identity, state ownership, and remote data.',['javascript','async','browser','react','state-management','typescript','nextjs','testing'],'Extend the task board with search and a reusable form state model.','Explain effects, cleanup, key identity, request boundaries, and a measured performance choice.'),
'backend-developer':('Backend Developer','Protect data and expose clear contracts.',['javascript','async','nodejs','api','express','mongodb','sql','security','testing','devops'],'Add an owner-scoped cursor endpoint with input validation and concurrency checks.','Pass two-user isolation, malformed-input, duplicate, persisted-conflict, and restart/recovery cases.'),
'nodejs-developer':('Node.js Developer','Understand the runtime and manage finite resources.',['javascript','async','nodejs','api','express','testing','engineering','devops'],'Build a streamed report and a bounded CPU-job worker.','Measure blocking, prove a concurrency cap, handle errors, and drain active work to a deadline.'),
'full-stack-engineer':('Full-Stack Engineer','Connect interface behavior to API and persistence guarantees.',['html','css','javascript','async','react','typescript','api','nodejs','express','mongodb','security','testing','engineering','git'],'Implement a user-visible feature from input through authoritative save and recovery.','Provide a contract, data model, browser demo, persisted tests, and a defended alternative.'),
'interview-preparation':('Interview Preparation','Prioritize product-company and startup evaluation while adapting to the actual role.',['javascript','async','react','nodejs','express','mongodb','security','testing','system-design','engineering'],'Use the existing 100-question bank, 24 scenarios, 16 timed exercises, and company worksheet.','Complete two timed builds and a project deep dive; repeat weak answers and use recruiter-confirmed process guidance.'),
'production-engineer':('Production Engineer','Operate safely under release, dependency, and data failure.',['security','testing','git','nodejs','devops','cloud','engineering','system-design','redis'],'Write and execute the production gate for a source project in a suitable environment.','Verify configuration, health, rollback, restore, safe logs, concurrency, and dependency-unavailable behavior.'),
'advanced-mern-engineer':('Advanced MERN Engineer','Study specialization because a workload justifies it.',['typescript','state-management','nextjs','mongoose','sql','redis','realtime','system-design','cloud','engineering'],'Design notifications or inventory with replay, duplicate delivery, and operational limits.','Defend consistency and freshness requirements; demonstrate a failure matrix and measured scaling decision.')}

# title, tier, technologies, features, invariant, data model, API contract, implementation status, source
PROJECTS={
'calculator':('Calculator','Beginner','HTML CSS JavaScript','Add, subtract, multiply, and divide two numbers; show validation; preserve inputs on failure.','Reject invalid inputs and division by zero without evaluating arbitrary expressions.','Local form inputs and a result/error state.','No network API.','implemented-learning','projects/knowledge-base/learning-lab'),
'todo':('Todo with undo','Beginner','HTML CSS JavaScript','Create, complete, delete, filter, and undo a deletion.','Undo restores the original id and position.','Local tasks with stable ids, completion, and bounded undo.','No network API.','implemented-learning','projects/knowledge-base/learning-lab'),
'quiz':('Quiz','Beginner','HTML CSS JavaScript','Answer questions, show progress and score, reset, and explain incorrect answers.','One answer per question contributes at most one score.','Questions, current index, selected answer, and score.','No network API.','implemented-learning','projects/knowledge-base/learning-lab'),
'weather':('Weather app','Beginner','HTML CSS JavaScript Fetch','Demo weather offline; optionally request weather for manually entered coordinates; handle timeout and failure.','Old responses cannot replace the latest requested location.','Coordinates, request generation, and loading/success/error state.','Optional Open-Meteo forecast request; no API key or geolocation required.','implemented-learning','projects/knowledge-base/learning-lab'),
'notes':('Local notes','Beginner','HTML CSS JavaScript','Create, select, edit, delete, and export plain-text notes; tolerate storage failures.','Titles render as data rather than executable markup.','Notes with stable ids, text, and selected id; local persistence.','No network API; JSON export is local.','implemented-learning','projects/knowledge-base/learning-lab'),
'expense-tracker':('Expense tracker','Beginner','HTML CSS JavaScript','Add exact two-decimal expenses, categorize, filter, delete, and calculate totals.','Store positive safe integer cents and compute totals from all relevant records.','Local records with id, category, and integer cents.','No network API.','implemented-learning','projects/knowledge-base/learning-lab'),
'blog':('Blog','Intermediate','React Node Express MongoDB','Draft, publish, edit, list, and search articles; validate title/body; enforce author ownership.','Only authorized authors can modify their drafts or publications.','Users and articles with author, status, timestamps, and version.','GET/POST articles; PATCH/DELETE an owned article; bounded query contract.','specification',''),
'movie-app':('Movie catalog','Intermediate','React HTTP API','Search, paginate, view details, and save favorites; provide loading and stale-response protection.','Detail and favorite state refer to stable movie ids, not array positions.','Local favorite ids and remote movie read models.','Use a verified movie API or checked-in fixtures; credentials stay server-side when required.','specification',''),
'youtube-clone':('Video catalog interface','Intermediate','React HTML media API','Browse videos, search, play owned/licensed sample media, and save a playlist.','Playback failures and missing captions remain visible; do not redistribute unlicensed media.','Videos, metadata, playlist ids, and playback state.','Bounded catalog reads; playlist writes if a backend is added.','specification',''),
'ecommerce-frontend':('E-commerce frontend','Intermediate','React state management','Browse products, sort/filter, update cart quantity, and display checkout estimates.','Client totals are presentation; final stock and price must be revalidated by a server.','Products and local cart quantities keyed by product id.','Fixture catalog initially; later server checkout contract.','specification',''),
'admin-dashboard':('Admin dashboard','Intermediate','React Express MongoDB','Filter and page records, view aggregates, edit permitted fields, and recover from forbidden actions.','A visible admin screen never substitutes for server permissions.','Permission-scoped read models and audited changes.','Bounded admin reads and allowlisted writes with trusted roles.','specification',''),
'kanban':('Kanban board','Intermediate','MongoDB Express React Node','Create, move, delete, and reconcile conflicting task edits.','Two writes using the same stored version cannot both succeed.','Owned tasks with status and version.','Existing task CRUD contract in the MERN workspace.','implemented-learning','projects/interview-ready/mern-workspace'),
'chat':('Chat application','Intermediate','React Node Socket.IO MongoDB','Join authorized rooms, send messages, view history, and recover after reconnect.','Room membership is checked server-side and durable messages have stable ids.','Rooms, memberships, messages, and replay positions.','Authorized history reads and event writes; documented acknowledgement semantics.','specification',''),
'mern-ecommerce':('Full MERN e-commerce','Advanced','MERN queues optional Redis','Catalog, cart, order, inventory reservation, payment-provider test integration, and order recovery.','No negative stock or duplicate paid business effect after replay.','Products, reservations, orders, operation ids, and outbox.','Versioned catalog/order contract with provider event verification and idempotency.','specification',''),
'lms':('Learning management system','Advanced','MERN media storage','Course authoring, enrollment, lessons, progress, and permission-scoped teaching views.','Enrollment and progress writes are scoped to the permitted account and course.','Users, courses, enrollment, lesson versions, and progress.','Course and enrollment APIs with bounded lists and protected media access.','specification',''),
'job-portal':('Job portal','Advanced','MERN or PostgreSQL','Publish jobs, search/filter, apply, upload constrained documents, and review applications.','One applicant/job pair has one active application; employers see only permitted submissions.','Jobs, organizations, memberships, applications, and file references.','Search, application create/status, organization permissions, and safe uploads.','specification',''),
'social-network':('Social network','Advanced','MERN queues','Profiles, follow relationships, posts, feed continuation, moderation, and privacy settings.','Feed and media access respect visibility and ownership, including after cache invalidation.','Profiles, follows, posts, visibility, moderation state, and cursor records.','Bounded feed and post contract; trusted moderation operations.','specification',''),
'project-platform':('Project management platform','Advanced','MERN optional real-time','Teams, projects, tasks, comments, roles, audit history, and notification recovery.','Every operation validates tenant membership and persisted task version.','Organizations, memberships, projects, tasks, comments, outbox, and audit events.','Tenant-scoped CRUD, cursor history, role permissions, and notifications.','foundation-implemented','projects/interview-ready/mern-workspace'),
'realtime-chat':('Recoverable real-time chat','Advanced','MERN Socket.IO optional Redis','Durable messages, replay, attachment constraints, delivery/read states, and multi-instance routing.','Reconnect and duplicate delivery do not lose or repeat a durable message in the view.','Rooms, memberships, messages, acknowledgements, and replay positions.','Authorized history cursor plus event protocol with stable ids.','specification',''),
'expense-platform':('Expense management platform','Advanced','MERN','Exact amounts, categories, date validation, account reporting, organizational approvals, and audit.','Money and owner scope remain correct across list truncation, concurrent approval, and replay.','Owned expenses, organization membership, approval versions, and audit records.','Existing expense CRUD/summary foundation; approvals and organization scope remain extensions.','foundation-implemented','projects/interview-ready/mern-workspace')}

# Verified core implementations share a package; larger requirements remain explicit extensions.
CORE={
 'blog':'Draft/publish/edit/delete articles, literal search and cursor lists with author ownership and stored versions.',
 'movie-app':'Original fixture search, pagination, detail and persistent account favorites.',
 'youtube-clone':'Original captioned WebM playback, missing-media feedback and persistent playlists; catalog search API.',
 'ecommerce-frontend':'Catalog, local cart quantities and estimates, server-authoritative single-product orders and cancellation.',
 'admin-dashboard':'Owner-only workspace aggregates, expense totals and paged audit history.',
 'chat':'Authorized rooms, durable HTTP message writes, stable operation IDs and SSE replay.',
 'mern-ecommerce':'Atomic one-SKU stock/order reservation, idempotency, cancellation and signed payment test contracts; no real payment service.',
 'lms':'Workspace course authoring, enrollment-gated text lessons and persisted lesson completion.',
 'job-portal':'Job search, unique applications, staff review and restricted tiny PDF attachment API.',
 'social-network':'Follow relationships, plain-text posts, privacy changes and permission-filtered cursor feeds.',
 'project-platform':'Workspace roles, projects, versioned tasks, comments, transactional audit and recoverable notifications.',
 'realtime-chat':'Persisted message IDs, operation replay/collision checks, SSE Last-Event-ID replay and session/membership rechecks.',
 'expense-platform':'Exact cents, dates/categories, organization scope, independent approval, stored versions and transactional audit.'}
for project_id in CORE:
    row=list(PROJECTS[project_id]);row[7]='implemented-learning';row[8]='projects/interview-ready/mern-workspace'
    if project_id in ['chat','realtime-chat']:row[2]='React Node Express MongoDB Server-Sent Events'
    PROJECTS[project_id]=tuple(row)

def build(root,write,areas):
    import json
    overview='# Learning paths\n\nChoose a goal, follow prerequisite edges, and use the exit evidence rather than the number of pages read. Study estimates describe first practice, not guaranteed mastery.\n\n'
    routeData=[]
    for id,(title,goal,steps,practice,exit) in PATHS.items():
        overview+=f'- [{title}]({id}.md) — {goal}\n'
        text=f'# {title}\n\n{goal}\n\n[All paths](README.md) · [Priority system](../README.md) · [Coverage](../COVERAGE.md)\n\n## Sequence and priority\n\n'
        for n,step in enumerate(steps,1):text+=f'{n}. [{areas[step]["title"]}](../topics/{step}.md) — focus P0/P1 first; follow linked prerequisites.\n'
        text+='\n## Practice and exit evidence\n\n'+practice+'\n\n'+exit+'\n\n## Review and next step\n\nRecord a failed boundary or unclear explanation, repeat it with a changed input, and move to the next requirement only when you can demonstrate the behavior. Use [project status](../projects/README.md) to distinguish source from specifications.\n'
        if id=='interview-preparation':text+='\n[Question bank](../../interview-handbook/questions/index.md) · [Scenarios](../../interview-handbook/scenarios/README.md) · [Timed builds](../../interview-handbook/machine-coding/README.md) · [Company playbooks](../../interview-handbook/companies/README.md) · [Project defense](../../interview-handbook/companies/project-defense.md) · [Study planner](../../interview-handbook/downloads/README.md)\n'
        write(f'knowledge-base/paths/{id}.md',text);routeData.append(dict(id=id,title=title,guideIds=steps,path=f'knowledge-base/paths/{id}.md',exitEvidence=exit))
    write('knowledge-base/paths/README.md',overview)
    write('knowledge-base/data/paths.json',json.dumps(routeData,indent=2))
    text='# Project ladder\n\nAll 20 entries have runnable core learning source. Six beginner apps use the web learning lab; the remaining entries use distinct workflows in a shared MERN package. Larger requirements remain explicit extensions in the [product scope matrix](../../projects/interview-ready/mern-workspace/PRODUCT_LAB.md). None is certified production-ready. [Production gate](PRODUCTION_GATE.md) defines the evidence needed before deployment. [Original 150 briefs](../../PROJECT_INDEX.md) remain additional choices.\n\n| Project | Tier | Status | Source or packet |\n| --- | --- | --- | --- |\n'
    registry=[]
    for id,(title,tier,tech,features,invariant,model,api,status,source) in PROJECTS.items():
        text+=f'| [{title}]({id}.md) | {tier} | {status} | '+(f'[Source](../../{source}/README.md)' if source else 'Packet; source not yet implemented')+' |\n'
        packet=f'# {title}\n\nDifficulty: {tier}\n\nTechnology: {tech}\n\nImplementation status: **{status}**\n\n## Requirements\n\n{features}\n\n## Features\n\n{features}\n\n## Architecture\n\nSeparate presentation, validated domain inputs, and persistence or external reads. The key invariant is: **{invariant}**\n\n## Database schema\n\n{model}\n\n## API specification\n\n{api}\n\n## Folder structure\n\n'
        packet+=f'Canonical implementation: `{source}/`.\n\n' if source else 'Proposed source: `client/`, `server/`, `test/`, and a root README/manifest. This is a design packet; those folders are not claimed to exist.\n\n'
        packet+='## Implementation\n\n'+(f'[Read and run the existing source](../../{source}/README.md). ' if source else 'This project is a specification with no implemented source in this packet. ')
        if status=='foundation-implemented':packet+='The linked source supplies a domain foundation only; organization, approval, audit, or multi-project capabilities above remain unimplemented. '
        if id in CORE:packet=packet.rstrip()+'\n\n**Implemented core:** '+CORE[id]+'\n\nThe requirements above describe the wider target. Compare them with the [implemented scope and extension matrix](../../projects/interview-ready/mern-workspace/PRODUCT_LAB.md), which also contains actual routes, source layout, data model and guarantees. `npm run demo` starts a disposable replica set without Docker. '
        packet+='Check the actual source README before claiming a feature works.\n\n## Testing\n\nDemonstrate the invariant with expected outcomes. Include empty input, invalid input, failure recovery, and keyboard behavior. Persistent versions, uniqueness, or authorization require realistic integration checks when applicable. The shared MERN package includes real MongoDB tests and browser checks for the product workflows.\n\n## Deployment\n\nLearning use follows the source README. A production release must pass the [production gate](PRODUCTION_GATE.md), including runtime-specific configuration and recovery. No hosted deployment is implied by this packet.\n\n## Future improvements\n\nChoose one failure or scale requirement, implement it, and update source and tests before changing status. Avoid expanding scope without evidence.\n\n[All projects](README.md) · [Debugging library](../debugging/README.md)\n'
        write(f'knowledge-base/projects/{id}.md',packet);registry.append(dict(id=id,title=title,tier=tier,status=status,sourcePath=source or None,path=f'knowledge-base/projects/{id}.md',invariant=invariant))
    write('knowledge-base/projects/README.md',text);write('knowledge-base/data/projects.json',json.dumps(registry,indent=2))
